#!/usr/bin/env python3
"""
build_html.py -- bundle the SOMA interpreter and examples into ONE standalone
HTML file that runs the real Python toolchain in the browser via Pyodide.

The output is self-contained except for the Pyodide runtime, which it loads from
the official CDN (Pyodide is ~10 MB of WebAssembly and cannot be reasonably
inlined). Everything else -- the full soma package, every example, the bridge --
is embedded as JSON, written to Pyodide's virtual filesystem at startup, and
imported normally. This guarantees the playground's output is identical to
`python -m soma`.
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))


def gather():
    bundle = {}
    soma_dir = os.path.join(HERE, "soma")
    for fn in sorted(os.listdir(soma_dir)):
        if fn.endswith(".py"):
            with open(os.path.join(soma_dir, fn)) as f:
                bundle["soma/" + fn] = f.read()
    # the narrative authoring subpackage, so it can be imported in-browser too
    nar_dir = os.path.join(soma_dir, "narrative")
    if os.path.isdir(nar_dir):
        for fn in sorted(os.listdir(nar_dir)):
            if fn.endswith(".py"):
                with open(os.path.join(nar_dir, fn)) as f:
                    bundle["soma/narrative/" + fn] = f.read()
    with open(os.path.join(HERE, "web_bridge.py")) as f:
        bundle["web_bridge.py"] = f.read()

    examples = {}
    ex_dir = os.path.join(HERE, "examples")
    for fn in sorted(os.listdir(ex_dir)):
        if fn.endswith(".soma"):
            with open(os.path.join(ex_dir, fn)) as f:
                examples[fn[:-5]] = f.read()
    tut_dir = os.path.join(HERE, "tutorial")
    for fn in ("01_hello", "02_arbitration", "03_opaque"):
        p = os.path.join(tut_dir, fn + ".soma")
        if os.path.exists(p):
            with open(p) as f:
                examples["tutorial/" + fn] = f.read()
    # a showcase: the SOMA that soma.narrative generates from a short script,
    # so playground visitors can see what the high-level library produces.
    try:
        import sys as _sys
        _sys.path.insert(0, HERE)
        import importlib
        mod = importlib.import_module("examples.narrative.a_marriage")
        examples["narrative/a_marriage (generated)"] = (
            "// This program was GENERATED by the soma.narrative library from a\n"
            "// ~15-line Python script (examples/narrative/a_marriage.py).\n"
            "// The library lets authors write in characters and feelings; this\n"
            "// is the ordinary SOMA it compiles to.\n\n"
            + mod.build().source())
        saga = importlib.import_module("examples.narrative.the_house")
        examples["narrative/the_house (generated)"] = (
            "// GENERATED by soma.narrative from examples/narrative/the_house.py\n"
            "// -- a three-generation saga in ~20 lines of Python. Inherited\n"
            "// trauma is transmitted face-to-face down a lineage; the suggested\n"
            "// perturbation asks whether the granddaughter can be freed of it.\n\n"
            + saga.build().source())
        dip = importlib.import_module("examples.narrative.the_diplomat")
        examples["narrative/the_diplomat (generated)"] = (
            "// GENERATED by soma.narrative from examples/narrative/the_diplomat.py\n"
            "// -- a study of a man defended against his own longing: he wants and\n"
            "// fears being known at once, holds a value about honesty and breaks\n"
            "// it under pressure. Run `sift` to read the character.\n\n"
            + dip.build().source())
        sis = importlib.import_module("examples.narrative.two_sisters")
        examples["narrative/two_sisters (generated)"] = (
            "// GENERATED by soma.narrative from examples/narrative/two_sisters.py\n"
            "// -- two sisters at the reading of a will. Character is relational:\n"
            "// one composes her resentment, the other misreads the composed face.\n"
            "// `sift` recovers the gap the plot never states.\n\n"
            + sis.build().source())
        neg = importlib.import_module("examples.narrative.the_negotiator")
        examples["narrative/the_negotiator (generated)"] = (
            "// GENERATED by soma.narrative from examples/narrative/the_negotiator.py\n"
            "// -- the most complete character the library builds: a hostage\n"
            "// negotiator with internal parts (a protector who speaks, an exile\n"
            "// whose terror never ignites), a relational self, ambivalence, and a\n"
            "// value she breaks. Run `sift` -- the whole divided psyche is there.\n\n"
            + neg.build().source())
        unm = importlib.import_module("examples.narrative.the_unmooring")
        examples["narrative/the_unmooring · combs (generated)"] = (
            "// GENERATED by soma.narrative from examples/narrative/the_unmooring.py\n"
            "// -- co-regulation, from THE UNMOORING: Topman's grief is not argued\n"
            "// away but carried. Once Rover is present and steady, the *trust* in\n"
            "// the alarm falls while the belief is untouched. Sift for 'held in\n"
            "// the dark' -- presence, not persuasion.\n\n"
            + unm.build_combs().source())
        examples["narrative/the_unmooring · the run (generated)"] = (
            "// GENERATED by soma.narrative from examples/narrative/the_unmooring.py\n"
            "// -- confidence as belief about other people's belief. Five creditors\n"
            "// hold war-paper 'sound' only because the others do; shock one, and\n"
            "// the rest let go in a rush. Sift for 'the run': nothing, nothing,\n"
            "// then everything at once.\n\n"
            + unm.build_greywater().source())
        examples["narrative/the_unmooring · Blade's lie (generated)"] = (
            "// GENERATED by soma.narrative from examples/narrative/the_unmooring.py\n"
            "// -- the wound, the lie, and the arc. Blade's lie ('if I'm not ranked\n"
            "// above them I'm the surplus again') reads the equal regard that would\n"
            "// disconfirm it and SUPPRESSES it -- self-deception, in SOMA's own\n"
            "// precision arbitration -- so it only hardens: the tragic arc. Sift\n"
            "// for 'the lie kept' and 'a need the want never feeds'.\n\n"
            + unm.build_ring().source())
    except Exception:
        pass
    return bundle, examples


# ordering for the example menu: simple -> complex, teaching files first
EXAMPLE_ORDER = [
    "tutorial/01_hello", "tutorial/02_arbitration", "tutorial/03_opaque",
    "bad_news", "phantom_limb", "rubber_hand", "flashback",
    "workspace", "rebus", "split_brain", "trauma",
    "in_love", "the_look", "a_marriage", "the_dinner_party",
    "the_appointment", "the_inheritance", "the_interrogation",
    "grief", "chronic_pain",
    "narrative/a_marriage (generated)",
    "narrative/the_house (generated)",
    "narrative/the_diplomat (generated)",
    "narrative/two_sisters (generated)",
    "narrative/the_negotiator (generated)",
    "narrative/the_unmooring · combs (generated)",
    "narrative/the_unmooring · the run (generated)",
    "narrative/the_unmooring · Blade's lie (generated)",
]

# a friendly label + one-line blurb + a suggested perturbation for each
META = {
    "tutorial/01_hello":       ("01 · hello", "the smallest useful program", ""),
    "tutorial/02_arbitration": ("02 · arbitration", "perceive vs. act, one dial apart", ""),
    "tutorial/03_opaque":      ("03 · opaque (fails)", "a deliberate type error", ""),
    "bad_news":       ("bad_news", "feeling, and the lie told before it is known", ""),
    "phantom_limb":   ("phantom_limb", "the body schema still reaches", ""),
    "rubber_hand":    ("rubber_hand", "ownership migrates, then breaks", ""),
    "flashback":      ("flashback", "a memory with a body and no story", ""),
    "workspace":      ("workspace", "the bid for consciousness that loses", ""),
    "rebus":          ("rebus", "relaxing a belief hardened into a body", ""),
    "split_brain":    ("split_brain", "the interpreter that won't say 'I don't know'", ""),
    "trauma":         ("trauma", "dissociation as a supervisor that crashes", ""),
    "in_love":        ("in_love", "prediction error, rewarded", "courtship.learn=0.12"),
    "the_look":       ("the_look", "two people misreading each other", ""),
    "a_marriage":     ("a_marriage", "thirty years; love learned into contempt", ""),
    "the_dinner_party": ("the_dinner_party", "three bodies, one spotlight each", "consciousness.threshold=0.40"),
    "the_appointment": ("the_appointment", "precision talked out of itself", "believing_her.conviction=0.05"),
    "the_inheritance": ("the_inheritance", "a fear given before the evidence", "watching_her.learn=0.0"),
    "the_interrogation": ("the_interrogation", "a continuous account of a discontinuous self", ""),
    "grief":          ("grief", "the body reaching after the mind accepts", ""),
    "narrative/a_marriage (generated)": ("narrative · a_marriage", "generated by soma.narrative from ~15 lines of Python", "appraising_her_face.learn=0.0"),
    "narrative/the_house (generated)": ("narrative · the_house", "three-generation saga; inherited trauma, generated from ~20 lines", "Ada.face.gain=0.03"),
    "narrative/the_diplomat (generated)": ("narrative · the_diplomat", "a man defended against his own longing; try the sift", "Rader_wants_being_known.gain=0.0"),
    "narrative/two_sisters (generated)": ("narrative · two_sisters", "character is relational; two portraits, one will", "Cleo.composure.gain=0.0"),
    "narrative/the_negotiator (generated)": ("narrative · the_negotiator", "the most complete character: parts, relational self, a broken value", "Cass.appraising_pressure.precision=0.05"),
    "narrative/the_unmooring · combs (generated)": ("narrative · the_unmooring (combs)", "co-regulation: grief quieted by presence, not argument; sift 'held in the dark'", "Topman.rover_steadiness.gain=0.0"),
    "narrative/the_unmooring · the run (generated)": ("narrative · the_unmooring (the run)", "confidence as belief about belief; shock one holder and the rest cascade", ""),
    "narrative/the_unmooring · Blade's lie (generated)": ("narrative · the_unmooring (Blade's lie)", "the wound, the lie, the arc: a belief that suppresses its own disconfirming evidence and only hardens; sift 'the lie kept'", "the_lie_only_rank_makes_me_real.overwhelm=15"),
    "chronic_pain":   ("chronic_pain", "central sensitization; guarding builds the pain", ""),
}


def build():
    bundle, examples = gather()
    # keep only known examples, in order; append any not listed
    ordered = [k for k in EXAMPLE_ORDER if k in examples]
    for k in examples:
        if k not in ordered:
            ordered.append(k)
    ex_list = [{"key": k, "label": META.get(k, (k, "", ""))[0],
                "blurb": META.get(k, (k, "", ""))[1],
                "perturb": META.get(k, (k, "", ""))[2],
                "src": examples[k]} for k in ordered]

    payload = json.dumps({"files": bundle, "examples": ex_list})
    # Defensive: the payload is embedded as a JS literal inside <script>. Any
    # literal "</script" in the data (there is none today, but a future example
    # might add one) would prematurely close the tag. Escape it so the browser
    # sees the same string without the parser ever seeing a closing tag.
    payload = payload.replace("</", "<\\/")

    html = HTML_TEMPLATE.replace("/*__PAYLOAD__*/", payload)
    out = os.path.join(HERE, "soma_playground.html")
    with open(out, "w") as f:
        f.write(html)
    size = os.path.getsize(out)
    print(f"wrote {out} ({size/1024:.0f} KB, {len(ex_list)} examples, "
          f"{len(bundle)} python files)")
    return out


HTML_TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>SOMA — a playground for simulating the mind–body loop</title>
<style>
  :root{
    --bg:#0e1116; --panel:#161b22; --panel2:#1c222b; --ink:#d6dde6;
    --dim:#8b98a8; --line:#2a323d; --accent:#7fb0ff; --accent2:#a6e3a1;
    --warn:#f0a35e; --err:#ff8080; --mono:"SF Mono",ui-monospace,"Cascadia Code",
    "JetBrains Mono",Menlo,Consolas,monospace;
    --sans:ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;
  }
  *{box-sizing:border-box}
  html,body{margin:0;height:100%;background:var(--bg);color:var(--ink);
    font-family:var(--sans);font-size:14px}
  a{color:var(--accent);text-decoration:none}
  .wrap{display:flex;flex-direction:column;height:100vh;min-height:0}
  header{padding:12px 18px;border-bottom:1px solid var(--line);
    display:flex;align-items:baseline;gap:14px;flex-wrap:wrap}
  header h1{margin:0;font-size:17px;font-weight:640;letter-spacing:.2px}
  header .sub{color:var(--dim);font-size:12.5px}
  header .spacer{flex:1}
  header .hint{color:var(--dim);font-size:12px}
  .main{display:flex;flex:1;min-height:0}
  /* left rail: examples */
  .rail{width:230px;border-right:1px solid var(--line);overflow-y:auto;
    background:var(--panel);flex-shrink:0}
  .rail h2{font-size:11px;text-transform:uppercase;letter-spacing:.11em;
    color:var(--dim);margin:14px 14px 6px}
  .ex{padding:7px 14px;cursor:pointer;border-left:2px solid transparent}
  .ex:hover{background:var(--panel2)}
  .ex.active{background:var(--panel2);border-left-color:var(--accent)}
  .ex .nm{font-family:var(--mono);font-size:12.5px;color:var(--ink)}
  .ex .bl{font-size:11px;color:var(--dim);margin-top:1px;line-height:1.3}
  /* center: editor */
  .editor-col{display:flex;flex-direction:column;flex:1;min-width:0;
    border-right:1px solid var(--line)}
  .toolbar{display:flex;gap:6px;padding:8px 10px;border-bottom:1px solid var(--line);
    align-items:center;flex-wrap:wrap;background:var(--panel)}
  .toolbar .title{font-family:var(--mono);font-size:12.5px;color:var(--dim);
    margin-right:4px}
  button{font-family:var(--sans);font-size:12.5px;color:var(--ink);
    background:var(--panel2);border:1px solid var(--line);border-radius:6px;
    padding:5px 11px;cursor:pointer;transition:.12s}
  button:hover{border-color:var(--accent);color:#fff}
  button.primary{background:#243b66;border-color:#2f5290}
  button.primary:hover{background:#2a4576}
  button:disabled{opacity:.4;cursor:not-allowed}
  .toolbar .spacer{flex:1}
  .perturb-row{display:none;gap:6px;padding:6px 10px;border-bottom:1px solid var(--line);
    align-items:center;background:var(--panel)}
  .perturb-row.show{display:flex}
  .perturb-row label{font-size:12px;color:var(--dim)}
  .perturb-row input{font-family:var(--mono);font-size:12.5px;color:var(--ink);
    background:var(--bg);border:1px solid var(--line);border-radius:5px;
    padding:5px 8px;flex:1;min-width:120px}
  textarea{flex:1;width:100%;resize:none;border:0;outline:0;padding:14px 16px;
    background:var(--bg);color:var(--ink);font-family:var(--mono);
    font-size:13px;line-height:1.55;tab-size:2}
  /* right: output */
  .out-col{width:47%;display:flex;flex-direction:column;min-width:0;
    background:#0b0e13}
  .out-head{padding:8px 12px;border-bottom:1px solid var(--line);
    color:var(--dim);font-size:11.5px;text-transform:uppercase;letter-spacing:.1em;
    display:flex;align-items:center;gap:10px;background:var(--panel)}
  .out-head .badge{font-family:var(--mono);text-transform:none;letter-spacing:0;
    color:var(--accent);font-size:12px}
  .output{flex:1;overflow:auto;padding:12px 14px;margin:0;
    font-family:var(--mono);font-size:12px;line-height:1.35;white-space:pre;
    color:var(--ink);-webkit-overflow-scrolling:touch;overscroll-behavior:contain}
  .output.wrap-lines{white-space:pre-wrap;word-break:break-word}
  .fbtn{padding:2px 8px;font-size:12px;line-height:1.2;border-radius:5px}
  /* ANSI colors */
  .a-red{color:#ff8f8f}.a-green{color:#a6e3a1}.a-yellow{color:#f5d67b}
  .a-blue{color:#8fb8ff}.a-magenta{color:#e0a3f0}.a-cyan{color:#8fe6e0}
  .a-grey{color:#7c8797}.a-dim{color:#6d7887}.a-bold{font-weight:700;color:#fff}
  .status{padding:6px 14px;font-size:12px;color:var(--dim);
    border-top:1px solid var(--line);background:var(--panel);min-height:28px}
  .status.busy{color:var(--warn)}
  .status.ok{color:var(--accent2)}
  .status.err{color:var(--err)}
  .loading-splash{position:fixed;inset:0;background:var(--bg);z-index:50;
    display:flex;flex-direction:column;align-items:center;justify-content:center;
    gap:16px;text-align:center;padding:24px}
  .loading-splash h1{font-size:22px;margin:0;font-weight:640}
  .loading-splash p{color:var(--dim);max-width:440px;line-height:1.5;margin:0}
  .spinner{width:32px;height:32px;border:3px solid var(--line);
    border-top-color:var(--accent);border-radius:50%;animation:spin 0.9s linear infinite}
  @keyframes spin{to{transform:rotate(360deg)}}
  .kbd{font-family:var(--mono);background:var(--panel2);border:1px solid var(--line);
    border-radius:4px;padding:1px 5px;font-size:11px;color:var(--dim)}
  @media (max-width:860px){
    header .sub{display:none}
    header .hint{display:none}
    .rail{position:fixed;left:0;top:0;bottom:0;z-index:30;width:78%;max-width:300px;
      transform:translateX(-100%);transition:transform .2s;box-shadow:2px 0 16px #0008}
    .rail.open{transform:translateX(0);display:block}
    .main{flex-direction:column}
    .editor-col{border-right:0;border-bottom:1px solid var(--line);min-height:0;
      flex:1 1 42%}
    .out-col{width:100%;flex:1 1 58%;min-height:0}
    .toolbar{overflow-x:auto;flex-wrap:nowrap;-webkit-overflow-scrolling:touch}
    .toolbar .spacer{display:none}
    textarea{font-size:12.5px}
    .rail-backdrop.show{display:block}
  }
  @media (min-width:861px){ .menu-btn{display:none} }
  .menu-btn{background:var(--panel2);border:1px solid var(--line);border-radius:6px;
    padding:5px 10px;cursor:pointer;color:var(--ink);font-size:13px}
  .rail-backdrop{display:none;position:fixed;inset:0;background:#0009;z-index:25}
</style>
</head>
<body>
<div class="loading-splash" id="splash">
  <div class="spinner"></div>
  <h1>SOMA</h1>
  <p id="splash-msg">Loading the Python runtime in your browser…<br>
    <span style="font-size:12px">This runs the real interpreter (via Pyodide),
    so first load fetches ~10&nbsp;MB. It is cached afterwards.</span></p>
</div>

<div class="wrap">
  <header>
    <button class="menu-btn" id="menu-btn" aria-label="examples">☰</button>
    <h1>SOMA</h1>
    <span class="sub">a language for simulating the mind–body loop · runs the real interpreter in your browser</span>
    <span class="spacer"></span>
    <span class="hint">Run: <span class="kbd">Ctrl/⌘ + Enter</span></span>
  </header>

  <div class="main">
    <nav class="rail" id="rail">
      <h2>Examples</h2>
      <div id="ex-list"></div>
    </nav>
    <div class="rail-backdrop" id="rail-backdrop"></div>

    <div class="editor-col">
      <div class="toolbar">
        <span class="title" id="cur-title">untitled.soma</span>
        <button class="primary" id="btn-run" data-cmd="run">▶ Run</button>
        <button id="btn-check" data-cmd="check">Check</button>
        <button id="btn-sift" data-cmd="sift">Sift</button>
        <button id="btn-prose" data-cmd="prose">Prose</button>
        <button id="btn-trace" data-cmd="trace">Trace</button>
        <button id="btn-query" data-cmd="query">Query</button>
        <button id="btn-perturb" data-cmd="perturb">Perturb…</button>
        <span class="spacer"></span>
        <button id="btn-new">New</button>
      </div>
      <div class="perturb-row" id="perturb-row">
        <label>--set</label>
        <input id="perturb-input" placeholder="loop.precision=0.5  (change one dial, diff the story)">
        <button class="primary" id="btn-perturb-go">Diff</button>
      </div>
      <textarea id="code" spellcheck="false" autocomplete="off"></textarea>
    </div>

    <div class="out-col">
      <div class="out-head">
        Output <span class="badge" id="out-cmd"></span>
        <span class="spacer" style="flex:1"></span>
        <button class="fbtn" id="font-dec" title="smaller text">A−</button>
        <button class="fbtn" id="font-inc" title="larger text">A+</button>
        <label style="text-transform:none;letter-spacing:0;font-size:11px;color:var(--dim);margin-left:8px">
          <input type="checkbox" id="wrap-toggle"> wrap</label>
      </div>
      <pre class="output" id="output"></pre>
      <div class="status" id="status">initializing…</div>
    </div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/pyodide/v0.26.2/full/pyodide.js"></script>
<script>
const PAYLOAD = /*__PAYLOAD__*/;

// ---- ANSI -> HTML ---------------------------------------------------------
const ANSI_CLASS = {
  "31":"a-red","32":"a-green","33":"a-yellow","34":"a-blue",
  "35":"a-magenta","36":"a-cyan","90":"a-grey","2":"a-dim","1":"a-bold"
};
function esc(s){return s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");}
function ansiToHtml(text){
  // split on escape sequences; track open spans
  const parts = text.split(/\x1b\[([0-9;]*)m/);
  let html = "", open = 0;
  for(let i=0;i<parts.length;i++){
    if(i%2===0){ html += esc(parts[i]); }
    else{
      const codes = parts[i].split(";").filter(x=>x!=="");
      if(codes.length===0 || codes.includes("0")){
        while(open>0){ html+="</span>"; open--; }
      }
      for(const c of codes){
        if(c==="0"){ continue; }
        const cls = ANSI_CLASS[c];
        if(cls){ html += `<span class="${cls}">`; open++; }
      }
    }
  }
  while(open>0){ html+="</span>"; open--; }
  return html;
}

// ---- UI refs --------------------------------------------------------------
const $ = id => document.getElementById(id);
const codeEl=$("code"), outEl=$("output"), statusEl=$("status"),
      outCmdEl=$("out-cmd"), curTitleEl=$("cur-title");
let pyodide=null, bridge=null, currentKey=null, busy=false;

// ---- example list ---------------------------------------------------------
function titleForKey(k){
  const base = k.includes("/") ? k.split("/").pop() : k;
  return base + ".soma";
}
function buildExampleList(){
  const list=$("ex-list");
  for(const ex of PAYLOAD.examples){
    const div=document.createElement("div");
    div.className="ex"; div.dataset.key=ex.key;
    div.innerHTML=`<div class="nm">${esc(ex.label)}</div>`+
      (ex.blurb?`<div class="bl">${esc(ex.blurb)}</div>`:"");
    div.onclick=()=>loadExample(ex.key);
    list.appendChild(div);
  }
}
function loadExample(key){
  const ex=PAYLOAD.examples.find(e=>e.key===key);
  if(!ex) return;
  codeEl.value=ex.src;
  currentKey=key;
  curTitleEl.textContent=titleForKey(key);
  document.querySelectorAll(".ex").forEach(e=>
    e.classList.toggle("active",e.dataset.key===key));
  // stash a suggested perturbation
  $("perturb-input").value=ex.perturb||"";
  if(typeof closeRail==="function") closeRail();
  // auto-run the default view
  if(pyodide && !busy) runCommand("run");
}

// ---- running --------------------------------------------------------------
function currentTitle(){
  const t=curTitleEl.textContent.replace(/\.soma$/,"");
  return t.includes("/")?t.split("/").pop():t;
}
async function runCommand(cmd, extra){
  if(!pyodide || busy) return;
  busy=true; setStatus("running "+cmd+"…","busy");
  outCmdEl.textContent=cmd;
  try{
    const src=codeEl.value, title=currentTitle();
    const opts = Object.assign({rows:40, width:computeWidth()}, extra||{});
    // call the python bridge
    bridge.set_src(src, title, JSON.stringify(opts), cmd);
    const result = await pyodide.runPythonAsync(`
import json, web_bridge
_o = json.loads(_OPTS)
web_bridge.run_command(_CMD, _SRC, _TITLE, **_o)
`);
    lastCmd = cmd;
    outEl.innerHTML=ansiToHtml(result);
    outEl.scrollTop=0; outEl.scrollLeft=0;
    const clean = result.replace(/\x1b\[[0-9;]*m/g,"");
    if(clean.includes("\u2717")) setStatus("done — with an error (see output)","err");
    else setStatus("done","ok");
  }catch(e){
    outEl.textContent=String(e);
    setStatus("runtime error","err");
  }finally{ busy=false; }
}

// How many monospace columns fit in the output pane right now, at the current
// font size? The interpreter renders its boxes to exactly this width, so the
// dashboard, sift, and prose always fit without horizontal scroll -- on a phone
// or a wide desktop. (The trace is the one exception; it renders wide and
// scrolls, because its columns must stay aligned.)
function computeWidth(){
  const paneW = outEl.clientWidth || 600;
  const pad = 28;                       // matches .output horizontal padding
  const charW = fontSize * 0.6 + 0.1;   // monospace advance ~0.6em
  let cols = Math.floor((paneW - pad) / charW);
  cols = Math.max(30, Math.min(112, cols));
  return cols;
}

let lastCmd = "run";
function rerunForResize(){ if(pyodide && !busy && lastCmd) runCommand(lastCmd); }
function setStatus(msg, kind){
  statusEl.textContent=msg;
  statusEl.className="status"+(kind?(" "+kind):"");
}

// ---- wire buttons ---------------------------------------------------------
document.querySelectorAll("[data-cmd]").forEach(btn=>{
  btn.onclick=()=>{
    const cmd=btn.dataset.cmd;
    if(cmd==="perturb"){ $("perturb-row").classList.toggle("show"); $("perturb-input").focus(); return; }
    runCommand(cmd);
  };
});
$("btn-perturb-go").onclick=()=>{
  const expr=$("perturb-input").value.trim();
  if(!expr){ setStatus("enter a --set expression, e.g. loop.precision=0.5","err"); return; }
  runCommand("perturb",{set_expr:expr});
};
$("perturb-input").addEventListener("keydown",e=>{
  if(e.key==="Enter"){ e.preventDefault(); $("btn-perturb-go").click(); }
});
$("btn-new").onclick=()=>{
  codeEl.value=NEW_TEMPLATE; currentKey=null;
  curTitleEl.textContent="untitled.soma";
  document.querySelectorAll(".ex").forEach(e=>e.classList.remove("active"));
  $("perturb-input").value="";
  outEl.textContent=""; outCmdEl.textContent=""; setStatus("new program — edit and Run","");
  codeEl.focus();
};
$("wrap-toggle").onchange=e=>outEl.classList.toggle("wrap-lines",e.target.checked);

// mobile: slide-in examples rail
function closeRail(){ $("rail").classList.remove("open"); $("rail-backdrop").classList.remove("show"); }
function openRail(){ $("rail").classList.add("open"); $("rail-backdrop").classList.add("show"); }
$("menu-btn").onclick=()=>{ $("rail").classList.contains("open")?closeRail():openRail(); };
$("rail-backdrop").onclick=closeRail;

// font-size control (persists across runs; re-renders so boxes refit the width)
let fontSize = 12;
function applyFont(){
  outEl.style.fontSize = fontSize + "px";
  try{ localStorage.setItem("soma-font", String(fontSize)); }catch(e){}
}
$("font-inc").onclick=()=>{ fontSize=Math.min(20,fontSize+1); applyFont(); rerunForResize(); };
$("font-dec").onclick=()=>{ fontSize=Math.max(8,fontSize-1); applyFont(); rerunForResize(); };
(function(){ try{ const s=localStorage.getItem("soma-font"); if(s) fontSize=+s; }catch(e){} applyFont(); })();

// re-render on viewport changes so the width always matches the pane (rotate a
// phone, resize a window) -- debounced.
let resizeTimer=null;
window.addEventListener("resize",()=>{
  clearTimeout(resizeTimer);
  resizeTimer=setTimeout(rerunForResize,250);
});

// Ctrl/Cmd+Enter to run
codeEl.addEventListener("keydown",e=>{
  if((e.ctrlKey||e.metaKey)&&e.key==="Enter"){ e.preventDefault(); runCommand("run"); }
  // tab inserts two spaces
  if(e.key==="Tab"){ e.preventDefault();
    const s=codeEl.selectionStart, en=codeEl.selectionEnd;
    codeEl.value=codeEl.value.slice(0,s)+"  "+codeEl.value.slice(en);
    codeEl.selectionStart=codeEl.selectionEnd=s+2;
  }
});

const NEW_TEMPLATE = `// a new SOMA program.
// A body, a loop that reads it, and a stimulus from the world.

sim { duration: 6s  dt: 1s }

body Someone @cardiac {
  intero heart : BPM  baseline 70
}

stimulus heart { at 2s: 120 }

loop noticing @cardiac {
  prior:      predict(70)
  sense:      heart
  precision:  0.9
  conviction: 0.3
  act { emit feel(surprise) }
}
`;

// ---- boot -----------------------------------------------------------------
async function boot(){
  try{
    $("splash-msg").innerHTML="Downloading the Python runtime (Pyodide)…";
    pyodide = await loadPyodide();
    $("splash-msg").innerHTML="Installing the SOMA interpreter…";
    // write every bundled python file into the virtual FS
    const files = PAYLOAD.files;
    pyodide.FS.mkdirTree("soma");
    for(const [path, content] of Object.entries(files)){
      pyodide.FS.writeFile(path, content);
    }
    // make the working dir importable and pre-import the bridge
    await pyodide.runPythonAsync(`
import sys
sys.path.insert(0, "")
import web_bridge
`);
    // helper to shuttle args in without string-escaping headaches
    await pyodide.runPythonAsync(`
_SRC=""; _TITLE=""; _OPTS="{}"; _CMD="run"
def _set_src(s,t,o,c):
    global _SRC,_TITLE,_OPTS,_CMD
    _SRC=s; _TITLE=t; _OPTS=o; _CMD=c
import builtins as _b
`);
    bridge = { set_src:(s,t,o,c)=>{
      pyodide.globals.set("_SRC",s); pyodide.globals.set("_TITLE",t);
      pyodide.globals.set("_OPTS",o); pyodide.globals.set("_CMD",c);
    }};
    // Warm-up: run the smallest example once now, while the splash is still up.
    // This forces every module to import and compile, so the user's first real
    // click is fast. (The interpreter itself is milliseconds; this just moves
    // the one-time import cost out of the interactive path.)
    $("splash-msg").innerHTML="Warming up the interpreter…";
    try{
      bridge.set_src("sim { duration: 2s dt: 1s }\nbody b @cardiac { intero h : H baseline 1 }\nstimulus h { at 1s: 5 }\nloop l @neural { prior: predict(0) sense: h precision: 0.9 conviction: 0.2 act { emit feel(x) } }",
        "warmup", JSON.stringify({rows:2,width:60}), "run");
      await pyodide.runPythonAsync(`import json, web_bridge
web_bridge.run_command(_CMD, _SRC, _TITLE, **json.loads(_OPTS))`);
    }catch(e){ /* warm-up failure is non-fatal */ }
    // done
    $("splash").style.display="none";
    setStatus("ready","ok");
    buildExampleList();
    loadExample(PAYLOAD.examples[0].key);
  }catch(e){
    $("splash-msg").innerHTML="Failed to start: "+esc(String(e))+
      "<br><br>Check your connection — Pyodide loads from a CDN.";
  }
}
boot();
</script>
</body>
</html>
"""


if __name__ == "__main__":
    build()
