#!/usr/bin/env python3
"""
Generate TUTORIAL.md for the soma.narrative library.

The tutorial is a build product, not a hand-maintained file: every block of
source code in it is pulled straight from the real example modules with
`inspect.getsource`, and every block of output is captured by actually running
the code at build time. So the source is always complete and the output is
always exactly what the current library produces -- the two can never drift.

    python3 build_tutorial.py            # writes TUTORIAL.md

The prose (the explanations) lives here as strings; the code and output are
injected live. To regenerate after changing the library or an example, just run
this again.
"""
import io
import os
import re
import sys
import inspect
import contextlib

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, "examples", "narrative"))

_ANSI = re.compile(r"\x1b\[[0-9;]*m")


def strip(s: str) -> str:
    return _ANSI.sub("", s)


def src_of(fn) -> str:
    """The real source of a build function, dedented, decorators/blank-trimmed."""
    s = inspect.getsource(fn)
    return s.rstrip("\n")


def dashboard(story, width=78) -> str:
    return strip(story.run(width=width)).rstrip("\n")


def portrait(story, width=78) -> str:
    return strip(story.characterize(width=width)).rstrip("\n")


def prose(story) -> str:
    return strip(story.prose()).rstrip("\n")


def soma_src(story) -> str:
    return story.source().rstrip("\n")


def findings(story) -> str:
    """The real sift() output, wrapped to page width with a hanging indent so no
    text is lost but nothing runs off the edge."""
    import textwrap
    out = []
    for f in story.sift():
        line = f"[{f.pattern}] {f.text}"
        out.append(textwrap.fill(line, width=78, subsequent_indent="    "))
    return "\n".join(out)


def perturb(module_name, dial) -> str:
    mod = __import__(module_name)
    return strip(mod.build().perturb(dial)).rstrip("\n")


# a growing list of markdown chunks
DOC = []


def md(text: str):
    DOC.append(text.rstrip("\n"))


def code(text: str, lang="text"):
    DOC.append(f"```{lang}\n{text}\n```")


def py(fn):
    """Embed a build function's real source as a python block."""
    DOC.append("```python\n" + src_of(fn) + "\n```")


# ===========================================================================
#  Assemble the document
# ===========================================================================
def main():
    import importlib
    # import every example module we will quote or run
    import bad_news, the_look, a_marriage, the_house, the_diplomat
    import two_sisters, the_negotiator
    the_unmooring = importlib.import_module("the_unmooring")

    # -- also build the two small inline teaching examples live -------------
    from soma.narrative import Story, anxious, guarded

    def first_feeling():
        story = Story("first_feeling", span="6s", step="1s",
                      about="a first feeling")
        mara = story.character("Mara", temperament=anxious)
        mara.senses("phone")
        mara.appraises("phone", as_threat=True, feeling="dread",
                       when="phone > 3")
        mara.narrates(voice={"dread": "It's nothing. It's probably nothing."})
        story.at("2s", mara.hears("phone", 9))
        return story

    def a_glance():
        story = Story("a_glance", span="8s", step="1s", about="being seen")
        ida = story.character("Ida", temperament=anxious)
        theo = story.character("Theo", temperament=guarded)
        ida.reads(theo, "face", gain=0.9, lag="1s")
        ida.appraises("theo_face", feeling="shame", when="theo_face > 4")
        ida.narrates(voice={"shame": "He can see right through me."})
        story.at("2s", theo.shows("face", 9))
        return story

    # ----------------------------------------------------------------- intro
    md("""# SOMA by example: simulating characters that reveal themselves

*A complete, self-contained tutorial for the `soma.narrative` library — writing
simulated people whose bodies tell on them, and reading the novelistic insight
back out. Every line of code below is quoted from a runnable file, and every
block of output was produced by running that code; this document is generated by
`build_tutorial.py`, which captures both live, so nothing here can be stale.*

---

## What this is

SOMA is a small language for simulating the mind–body loop of a character. You
do not write what a character *does*; you write how they are *built* — what they
sense, what their body makes of it, what they feel, and the story they tell
themselves about it. Then you run the simulation and read what happened.

The payoff is a particular kind of insight. Because a character's narrator (the
voice in their head) and their body are *separate mechanisms*, they can
**disagree** — and that gap, logged event by event, is exactly the stuff of
novelistic characterization: the person who says *I'm fine* while their heart
races; the value held in words and broken in the flesh; the feeling that never
quite reaches awareness; the hunger the world keeps feeding and wiping.

This tutorial starts from a bare shell prompt and builds up to a whole novel's
cast. It is organized simple → complex, and every section shows you three
things: the **code** (what you wrote), the **output** (what running it
produced), and an **explanation** tying specific lines of output back to the
code and out to what they *mean* about the character.

You need no prior familiarity with the base SOMA language; the narrative library
sits on top of it, and we look at the generated SOMA only once, to prove there
is no magic underneath.

---

## 1. Getting it running

Everything lives in one Python package, `soma`, with a high-level authoring
layer at `soma.narrative`. You need **Python 3.10+** and, for the sparkline
plots in the dashboard, **numpy**.

Unzip the project and step inside:

```bash
unzip soma_lang.zip
cd soma_lang
```

Confirm the engine works by running the test suite — it should report all tests
passing:

```bash
python3 -m pytest -q
```

There are two ways to drive the library.

**The Python front end.** You write a `Story`, call methods on it to build up
characters, place a few events in time, and print a view. Save this as
`my_first.py` anywhere inside the project folder:

```python
import sys
sys.path.insert(0, ".")          # so `import soma` finds the package
from soma.narrative import Story, anxious

story = Story("first_feeling", span="6s", step="1s", about="a first feeling")
mara = story.character("Mara", temperament=anxious)
mara.senses("phone")
mara.appraises("phone", as_threat=True, feeling="dread", when="phone > 3")
mara.narrates(voice={"dread": "It's nothing. It's probably nothing."})
story.at("2s", mara.hears("phone", 9))

print(story.run())               # the dashboard
```

Run it:

```bash
python3 my_first.py
```

**The command-line front end** operates on `.soma` source files. The narrative
library can emit that source for you with `story.source()`, so a common workflow
is: prototype in Python, dump the generated SOMA, then explore it with the CLI
subcommands.

```bash
python3 -m soma run    my_first.soma   # the full dashboard
python3 -m soma sift   my_first.soma   # just the ranked findings
python3 -m soma prose  my_first.soma   # free-indirect prose
python3 -m soma trace  my_first.soma   # the raw event log, in full
python3 -m soma check  my_first.soma   # type/consent checks only
```

Every worked example in this tutorial is a shipped file under
`examples/narrative/`, and each one supports a set of flags so you can ask it for
any view directly:

```bash
python3 examples/narrative/bad_news.py             # dashboard (default)
python3 examples/narrative/bad_news.py --source    # the generated SOMA
python3 examples/narrative/bad_news.py --sift       # findings only
python3 examples/narrative/the_diplomat.py --character   # the portrait
python3 examples/narrative/the_unmooring.py combs --sift  # a named study
```

Nothing else needs installing. If a command in this tutorial is runnable as-is,
it is shown in a `bash` block; if it is a fragment to paste into a script, it is
shown in a `python` block.
""")

    # ------------------------------------------------ 2. the core idea
    md("""---

## 2. The core idea, in one character

The `my_first.py` you just ran is our first character, Mara. Those five lines of
intent map onto the four things every SOMA character is made of:

- **`senses`** — a channel onto the world. Mara can hear her `phone`.
- **`appraises`** — a *loop* that reads a channel and makes something of it. Mara
  treats the phone `as_threat`, and when it rings loudly enough
  (`when="phone > 3"`) the loop fires and she `feel`s `dread`.
- **the feeling** (a *quale*) — the feeling itself, which is *opaque*: the
  simulation records that dread happened, never what dread is made of. You can
  count feelings and compare them against what was said, but you cannot open one
  up. (This is a deliberate stance: the model refuses to pretend it knows the
  texture of an inner state.)
- **`narrates`** — the confabulating self, the voice in her head. Mara's voice
  insists *It's nothing. It's probably nothing.*

Here is the whole thing again, as a self-contained script:

```python
from soma.narrative import Story, anxious

story = Story("first_feeling", span="6s", step="1s", about="a first feeling")
mara = story.character("Mara", temperament=anxious)
mara.senses("phone")
mara.appraises("phone", as_threat=True, feeling="dread", when="phone > 3")
mara.narrates(voice={"dread": "It's nothing. It's probably nothing."})
story.at("2s", mara.hears("phone", 9))
print(story.run())
```

### What a loop actually does

Everything in SOMA is built from **loops**, and one idea makes them tick, drawn
from predictive-processing theory: a loop is always *predicting* what it will
sense, then comparing that prediction to what it actually senses. The mismatch is
the **error**, and what the loop does about the error is the whole game.

Each tick, an appraisal loop:

1. **predicts** a value (its *prior* — what it expects the channel to read),
2. **senses** the channel's real value,
3. computes the **error** between them, weighted by two dials — *precision*
   (trust in the senses) and *conviction* (trust in the prior), and
4. if the error clears a firing threshold, the loop **fires**: it runs its
   reaction (emitting a feeling, letting the narrator speak) and **arbitrates**
   what to do with the surprise. If it trusts its senses more it *perceives*
   (revises its belief toward the world); if it trusts its prior more it *acts*
   (holds the belief and pushes back on the world instead).

A small error changes nothing — the world matched the prediction, so there is
nothing to react to. Only a surprise large enough to clear the threshold makes
something happen. That is why Mara feels dread only when the phone crosses her
threshold: until the call lands, her calm prediction holds; when it lands, the
error spikes, the loop fires, and dread is emitted. Because she is `anxious`
(high conviction, low precision) she *acts* rather than perceives — she does not
revise her sense that something is wrong; she feels it, and narrates over it.

### What a temperament sets

A **temperament** is just a bundle of those dials, named so you never type raw
numbers to get a recognizable disposition. `anxious` runs low precision and high
conviction: the prior *something is wrong* outranks the evidence, so an anxious
character reacts to a threat that may not be there. The library ships eight —
`anxious`, `stoic`, `trusting`, `guarded`, `volatile`, `numb`, `tender`, and
`hollowed` — and you can override any single dial per loop (you will see
`precision=`, `conviction=`, and `learn=` used that way later). The full table is
in §8.

### Running it

`story.run()` prints a dashboard. Here is the real output:
""")
    code(dashboard(first_feeling(), width=74))
    md("""
Read it top to bottom.

- The **BODY** panel shows the `phone` channel spiking from 0 to 9 — the little
  block-glyph sparkline is the channel's value over the six seconds.
- The **NARRATOR vs GROUND TRUTH** panel is the heart of SOMA. On the left, what
  Mara *says* (*It's nothing*, tagged «downplays» because the narrator is
  downplaying a distress); on the right, what her body actually *did* (`feels
  Qualia<dread>`). They do not match, and the dashboard sets them side by side.
- The **WINNOW-S** panel is the automatic reading — more on it in a moment.
- The **CHRONICLE** panel is the raw event log: every `settle` (a loop
  resolving), `emit` (a feeling fired), and `narrate` (the voice speaking). It is
  the ground truth everything else is derived from. The header says how many of
  the total events are shown; to see them all, use the `trace` view (below).

### How to read a `settle` line

The chronicle's `settle` lines are the loop resolving, tick by tick, and they
carry the numbers from the four-step cycle above. Reading one:

```text
2.0s settle appraising_phone sense=9.0 belief=6.0 error=1.65 pi_s=0.55 route=act
```

means: at 2 seconds the `appraising_phone` loop **sensed** 9.0, **believed** (had
predicted) 6.0, so the raw surprise was +3.0, scaled by sensory precision
`pi_s=0.55` to an **error** of 1.65 — over the firing threshold, so the loop
fired — and it **routed** to `act` (held its prior and pushed back) rather than
`perceive` (revise toward the world), because Mara's conviction outranks her
precision. That single line is the whole model in motion: predict, sense, weigh,
fire, arbitrate.

### The generated SOMA (there is no magic underneath)

Those five lines of Python compiled to an ordinary SOMA program. You rarely need
to read it, but it is worth seeing once — the high-level library is a
convenience, not a separate engine:
""")
    code(soma_src(first_feeling()))
    md("""
You can see the loop's `prior`, `precision`, and `conviction` right there — the
dials the `anxious` temperament set. (The `learn: 0.03` line is a slow hardening
of the prior with use; it does nothing dramatic here, and gets a starring role in
§4.3.) Every guarantee of the base language holds: the feeling is opaque, the
`@consent` line is required because the program simulates distress, and the
narrator is a *separate* construct that subscribes to the loop and speaks over
it.

### The full event log

The dashboard's chronicle is curated; when you want *every* event, `trace` prints
the lot. Here is Mara's complete log — nineteen events, nothing elided:
""")
    # capture full trace via the CLI-equivalent: story has no trace() convenience,
    # so render the chronicle in full through the trace view of the source.
    ff = first_feeling()
    _ = ff.result()
    code(_trace_full(ff))
    md("""
Every `emit`/`narrate` pair after 2.0s is one tick of the same standoff: the body
emits dread, the narrator says *It's nothing*. Five ticks, five contradictions —
which is exactly what the two findings below will name.

### The sift: storyful moments, found automatically

The **WINNOW-S** panel is the payoff. It runs a library of *sifting patterns* —
the dramatic shapes a novelist hunts for — over the event log and reports what it
finds. `story.sift()` returns those findings directly:
""")
    code(findings(first_feeling()))
    md("""
Two findings, both true of Mara. *Retained residual*: the dread kept coming back
— the body would not let the question go. *Confabulation gap*: the narrator kept
insisting on calm, and — crucially — the finding is graded and *names what is
being denied*: it scores high precisely because dread pressed hard underneath the
words. Neither finding was authored; both were **found** in the event log. That
is the tutorial's whole thesis in miniature: you build a mechanism, and the
insight falls out of running it.
""")

    # (subsequent sections)
    _section_coupling(a_glance)
    _section_examples(bad_news, the_look, a_marriage, the_house, the_diplomat,
                      two_sisters, the_negotiator)
    _section_unmooring(the_unmooring)
    _section_prediction(the_unmooring)
    _section_closing()

    out = "\n\n".join(DOC) + "\n"
    with open(os.path.join(HERE, "TUTORIAL.md"), "w") as f:
        f.write(out)
    n = out.count("\n")
    print(f"wrote TUTORIAL.md ({len(out)} bytes, {n} lines)")


def _section_coupling(a_glance):
    md("""---

## 3. Two people: coupling

A single character can misread the world. Two characters can misread *each
other* — and that needs one new verb, `reads`, which creates a **coupling**. One
character reads another's *surface* (a face, a tone) — never their interior. You
can see someone's face; you cannot see their feeling.

```python
from soma.narrative import Story, anxious, guarded

story = Story("a_glance", span="8s", step="1s", about="being seen")
ida = story.character("Ida", temperament=anxious)
theo = story.character("Theo", temperament=guarded)

ida.reads(theo, "face", gain=0.9, lag="1s")     # she reads his face, a beat late
ida.appraises("theo_face", feeling="shame", when="theo_face > 4")
ida.narrates(voice={"shame": "He can see right through me."})

story.at("2s", theo.shows("face", 9))           # Theo's face does something
print(story.run())
```

`reads` gives Ida a new channel, `theo_face`, that tracks Theo's real face with a
`gain` (how strongly it registers) and a `lag` (how late). When his face rises,
the reading crosses her threshold, her loop fires, and she makes `shame` of it —
telling herself he can see through her.

Notice what is *not* here: `as_threat=True`. Ida does not go in expecting his face
to mean anything (her prior is a flat zero), so when it rises it is a genuine
surprise — a large error — and that is what makes the loop fire. Had we marked it
a threat, she would have *expected* the worst, her belief would already sit high,
and his real face would match it too closely to register. Small choices in how a
character is wired change what they can feel.
""")
    code(dashboard(a_glance(), width=74))
    md("""
The new **BETWEEN THEM** panel names the coupling: Theo's face becomes Ida's
sensation, one second late. The `couple` lines in the chronicle are that transfer
happening. And the NARRATOR vs GROUND TRUTH panel shows the familiar gap — she
says *He can see right through me* while the record simply says she felt shame.

Two things are worth pausing on. First, the coupling is one-directional here: Ida
reads Theo, but Theo is just a face — he has no interior of his own. (In §5.2 we
make it mutual, and the two readings feed each other into a spiral.) Second,
`shame` is *Ida's* invention. Nothing about Theo's face carries shame; she
manufactures it. That is what makes coupling dramatic rather than telepathic: the
reader supplies the meaning, and can be wrong.

### Prose

Any simulation can be rendered as free-indirect prose with `story.prose()`. It is
not generation — each sentence is a rendering of a logged event:
""")
    code(prose(a_glance()))
    md("""
*Her face was hot before she knew why* is the shame; *He can see right through me*
is the narrator; *It was not true* is the gap between them. The prose says nothing
the event log did not.
""")


def _section_examples(bad_news, the_look, a_marriage, the_house, the_diplomat,
                      two_sisters, the_negotiator):
    md("""---

## 4. The simulations, from simple to complex

The rest of the tutorial walks the shipped examples in `examples/narrative/`,
each introducing one or two new ideas. For each you get the code (the real
`build()` function, quoted from the file), what it is doing, and its real output.
Any of them runs directly, e.g. `python3 examples/narrative/bad_news.py`; to
paste a `build()` into your own script, open every file the same way:

```python
import sys
sys.path.insert(0, ".")
from soma.narrative import (Story, anxious, stoic, trusting, guarded,
                            volatile, numb, tender, hollowed, arc)

# ... paste a build() function here ...

story = build()
print(story.run())            # or .sift(), .characterize(), .prose()
```
""")

    # ---- 4.1 bad_news ----
    md("""### 4.1  `bad_news` — the body knows first

The smallest complete person: a woman takes a phone call. It introduces two
ideas. **`feels(from_body=...)`** reads a feeling *off the body* rather than
straight off the world — dread is what a racing heart *means*. And **`drives`**
lets an appraisal reach into physiology: hearing the words drives her heart.
Because the feeling follows the heart, and the heart follows the news, the order
on the page is: body first, feeling second, and the calm story she tells last of
all.
""")
    py(bad_news.build)
    md("""
Note `fades_to=70`: a driven channel decays back to rest, so the racing heart is
an *event* with a shape, not a permanent new floor. Here is the dashboard:
""")
    code(dashboard(bad_news.build(), width=78))
    md("""
Follow the causal chain in the CHRONICLE, which is the point of this example. At
2.0s the stimulus lands (`stimulus ear value=9.0`); the appraisal fires and
`drive`s the heart to 118; the `feeling_dread` loop, reading the racing heart,
`emit`s dread and `spend`s from the body budget to do it; only *then* does the
narrator `narrate` "I'm fine." Body, feeling, story — in that order, every tick.
The findings name the two halves of that gap:
""")
    code(findings(bad_news.build()))
    md("""
And the confabulation is graded and *named*: it does not merely say "the record
says otherwise," it says the words were told over `dread` breaking through nine
times — which is why it scores as high as it does. `bad_news` is deliberately
minimal, so you can see the whole mechanism at once.
""")

    # ---- 4.2 the_look ----
    md("""### 4.2  `the_look` — a misreading that feeds itself

Now both characters have interiors, and they read *each other*. The trick is
**`shows_on`**: when Ana feels shame, it shows on her face — which becomes the
very signal Ivo reads and makes contempt of. His contempt shows on *his* face,
which deepens her shame. A spiral, and nobody intends any of it. Each also keeps
a **`has_mood`** — a slow variable that accumulates a feeling and outlasts any
single moment.
""")
    py(the_look.build)
    md("""
(`as_threat=True` *does* fire here, unlike Ida in §3 — because the reading has
full `gain=1.0`. Ida read Theo at 0.9, so his face reached ~8.1, only a little
over her threat-prior; here each face reaches a full 9, clears the prior by a wide
margin, and the loops fire and keep firing. The lesson from both is the same: a
threat appraisal only feels something when the world overshoots what it already
expected.)
""")
    code(dashboard(the_look.build(), width=78))
    md("""
The **MOOD** panel is new: each sister's mood integrates her feeling and decays,
so the numbers you see are the *climate* of the evening, deepening turn by turn.
And the findings now include **a mood that sours** — the library reading the
*trajectory* of a mood, not just a moment:
""")
    code(findings(the_look.build()))
    md("""
The spiral is real, and it is *severable*: because it runs on the couplings,
cutting one (setting a `reads` gain to zero) makes the escalation fall apart. That
kind of test — change one dial, re-run, see what disappears — is what `perturb` is
for, and we return to it below.
""")

    # ---- 4.3 a_marriage ----
    md("""### 4.3  `a_marriage` — thirty years, and a prior that hardens

This one runs on the **biography clock** (`clock="life"`, one step per year) and
introduces **`learns`**. Soren, tender, delights in being surprised by his wife —
low conviction plus being wrong equals delight. But `learns(0.055)` makes the loop
*harden* with use: every confirmation makes his model of her a little more
certain, until — with `updates=True, stops_seeing=True` — the hardened prior
outranks his senses and he stops taking her in. Then she is gone, and a second
appraisal that still `expects=5` (her presence) finds absence, and grief.
""")
    py(a_marriage.build)
    md("""
The `arc.wobble(...) + arc.hold(0, ...)` builds the stimulus timeline: her face
varies for 24 years, then holds at zero. The findings compress three decades into
the shape of a marriage:
""")
    code(findings(a_marriage.build()))
    md("""
Read the arc straight down: **delight in error** (the wonder of being surprised by
her), **precision pathology** (he stopped listening — the prior hardened until it
suppressed her), **retained residual** grief where the delight used to be, and **a
turn in how they meet the world** (early on his loops mostly *perceived* her; late
they mostly *acted*, imposing his settled picture). A whole marriage — wonder,
habituation, loss — in about fifteen lines, and not one beat of it asserted: every
finding is measured off the run.
""")

    # ---- 4.4 the_house ----
    md("""### 4.4  `the_house` — trauma across three generations

The first genuinely large simulation: ninety years, three characters, and a fear
that passes down a lineage. It combines everything so far and adds two mechanisms.
**`remembers`** gives Vera a somatic memory — a flashback keyed to a cue, firing a
feeling with no story attached. **`dissociates_when`** gives her a supervisor that
detaches under overload and slowly repairs.

The transmission works face-to-face: Vera's terror `shows_on` her face; her
daughter Ada `reads` that face and makes dread of it (and, learning, hardens) —
and Ada's dread shows on *her* face, which her daughter Mira reads as an unease she
cannot name. The war reaches the granddaughter as weather.
""")
    py(the_house.build)
    md("""
This one is too tall to print whole; the findings are where you read it (run the
file itself for the full dashboard). Here is `story.sift()`:
""")
    code(findings(the_house.build()))
    md("""
Read down the findings and you can see the inheritance: dread and terror returning
for decades, dissociation rupturing and repairing, three moods souring across the
generations, Vera's `the_field` flashback firing *with no episodic trace* (a body
that remembers alone), and — near the bottom — Mira's confabulation, *I don't know
why, I just feel it sometimes.* The granddaughter feels the war she never lived.

#### Perturbation: is the inheritance load-bearing?

Here is the question a novelist actually wants to ask: *does the fear really reach
the third generation, or is Mira's unease her own?* The `perturb` mechanism
answers it. Sever the coupling from Ada to Mira — turn the gain of that one reading
down — re-run, and diff the findings:

```bash
python3 -c "
import sys; sys.path.insert(0, '.'); sys.path.insert(0, 'examples/narrative')
import the_house
print(the_house.build().perturb('Ada.face.gain=0.03'))
"
```

The result names exactly what changes:
""")
    code(perturb("the_house", "Ada.face.gain=0.03"))
    md("""
With the transmission cut, Mira's inherited unease disappears from the findings —
the granddaughter is freed of a fear she never understood. The mechanism was
load-bearing; the simulation *proves* the inheritance rather than asserting it.
""")

    # ---- 4.5 the_diplomat ----
    md("""### 4.5  `the_diplomat` — wanting, and a value broken

Back to one person, but a deep one. Three new ideas arrive together. **`wants`**
and **`fears`** on the *same channel* create **ambivalence**: two drives pulling
opposite ways, so Rader is drawn to being known and repelled by it at once, and
settles nowhere. **`values`** gives him a stated principle — *I would never lie to
her* — and the bodily condition under which he betrays it (composing his face).
And **`effortful`** appraisals must spend a finite attention spotlight
(`has_attention`); when it is exhausted they are *starved*, which is how a man too
busy holding himself together never quite feels his own longing.
""")
    py(the_diplomat.build)
    md("""
Running `--character` gives a synthesized **portrait** — not a log of what
happened, but a reading of who he is, drawn from the record:
""")
    code(portrait(the_diplomat.build(), width=78))
    md("""
Every line is derived: the ambivalence from the two drives, the broken value from
the betrayal loop, the defended feeling from the longing his attention is too
spent to let him feel, the story he tells from his most-repeated narration. He
*is* named, in the `about=` string, "a man defended against his own longing" — but
the portrait does not read that string. It reads the record: the `longing` loop
tried to fire and was starved of attention on most of its attempts, so the reading
names longing as the thing held out of reach. Author's intent and simulation
result agree because the mechanism was built to make them agree, not because a
label was copied across. The findings show the same structure from the event side:
""")
    code(findings(the_diplomat.build()))

    # ---- 4.6 two_sisters ----
    md("""### 4.6  `two_sisters` — character is relational

Two sisters at the reading of a will. The point of this one is contrast: the same
event lands in one room and makes two different people, and the `characterize`
reading recovers the difference the plot never states. Cleo is guarded and
composes her resentment behind a value about not caring for money; Immy is tender
and torn, reading Cleo's composed face and unable to tell what it means.
""")
    py(two_sisters.build)
    md("""
The dual portrait puts them side by side:
""")
    code(portrait(two_sisters.build(), width=78))
    md("""
Read together, the two portraits explain each other. Cleo's composed resentment is
*exactly* the thing Immy cannot read — *Is she angry with me? I can't tell.*
Character here is not a property of one person; it is what happens between them.
""")

    # ---- 4.7 the_negotiator ----
    md("""### 4.7  `the_negotiator` — the most complete character

The last of the core examples puts every layer on one person at once. Cass runs
hostage negotiations; she is, professionally, the calmest person in any room. The
simulation is built to show that the calm is a *structure with a cost*, and it
introduces the two deepest constructs in the library.

**Internal parts** (`part`) model a divided psyche. Each part is a sub-agent that
reacts to something and bids for consciousness at a *salience*. A loud protector
(the professional, salience 0.95) wins; a quiet exile (the frightened child,
salience 0.28) feels real terror that never crosses the threshold into awareness —
felt, never known.

**The relational self** (`with_person`) makes one person several. Cass runs
different precision and conviction with the subject at the door (wary) than with
the colleague in her ear (open) — the same body, two selves, indexed by whom she
is with.

On top of those sit the constructs you already know: ambivalence about the rapport
that would end the standoff, a candor value she breaks with every composed word, a
mood that depletes, and a narrator that insists she is fine.
""")
    py(the_negotiator.build)
    md("""
The findings read the whole divided psyche:
""")
    code(findings(the_negotiator.build()))
    md("""
And the portrait synthesizes it into a reading a novelist could put in a notebook:
""")
    code(portrait(the_negotiator.build(), width=78))
    md("""
Notice how the pieces cohere. The feeling she **defends against** (terror) is
exactly the one her exile **carries** and is never heard. The self she is **with
the subject** (wary) is not the self she is **with her partner** (tender). And the
value she **holds** is the one her composed voice **breaks**. None of this was
stated in the code as a conclusion; all of it was found in the run.

#### The perturbation that proves it

Is the calm really load-bearing — is the self-deception doing work? Turn down how
sharply she perceives the pressure and re-run:

```bash
python3 -c "
import sys; sys.path.insert(0, '.'); sys.path.insert(0, 'examples/narrative')
import the_negotiator
print(the_negotiator.build().perturb('Cass.appraising_pressure.precision=0.05'))
"
```
""")
    code(perturb("the_negotiator", "Cass.appraising_pressure.precision=0.05"))
    md("""
With the pressure no longer landing so hard, she stops composing her voice — and
the value-betrayal *and* the self-deceiving narration both vanish. The lie she
tells herself was structural: remove the pressure that requires it, and it is gone.
""")


def _section_unmooring(u):
    md("""---

## 5. A whole novel's cast: four deeper primitives

The examples so far cover the library's core. This section introduces four
constructs added to model a specific novel, *The Unmooring* — and they turn out to
be general tools for the ways a world gets inside a person: by feeding a hunger,
by sitting beside them, by making them believe what everyone else is seen to
believe, or by hollowing them out. Each study below is a function in the single
file `examples/narrative/the_unmooring.py`; run any of them with a name and a
flag, e.g.:

```bash
python3 examples/narrative/the_unmooring.py ring   --sift
python3 examples/narrative/the_unmooring.py combs  --sift
python3 examples/narrative/the_unmooring.py greywater --sift
python3 examples/narrative/the_unmooring.py fleet  --character
```

### 5.1  `craves` — a hunger the world can feed and charge for

`craves(name, fed_by=, feeling=, erased=)` gives a character a want a place can
supply and withdraw. The single dial `erased` decides a hunger's *fate*, and the
sift tells the three fates apart. This is Blade, in the fighting-ring: the ring
supplies a rank, and the nightly tide-clean wipes the floor, so the rank he won at
dawn is gone by the next tide and he must win it again. Around that one wiped
hunger he is built as a whole divided man — a loud, brave protector that speaks,
and, under it, the starved animal that never gets heard.
""")
    py(u.build_ring)
    md("""
The findings recover the whole figure — not just the addiction, but the divided
self around it:
""")
    code(findings(u.build_ring()))
    md("""
Read them together: **a hunger the world keeps wiping** (the ring, fed and erased,
the loop that never opens); **the value the body broke** (the fair share he swore
and cannot live inside); **the feeling the whole self defends against**
(worthlessness — the surplus he fears being); and **never ignited** — the *spare
animal* part that bids nineteen times and is never heard, drowned out by the loud
brave protector. That last pair is the mechanism of the man: the reason he is so
gloriously, visibly good is that the good, loud part is exactly what keeps the
starved, quiet part from ever reaching awareness.

The same hunger has a gentler fate in the *fleet* study, where Ink carries the
identical starved animal but it is fed by *reading*, which does not erase. Compare
the two findings the sift produces for that quiet, met hunger versus Sound's boat,
a want the world will not feed at all:
""")
    fleet = u.build()
    import textwrap
    fleet_hunger = "\n".join(
        textwrap.fill(f"[{f.pattern}] {f.text}", width=78,
                      subsequent_indent="    ")
        for f in fleet.sift()
        if "hunger" in f.pattern or "want the world" in f.pattern)
    code(fleet_hunger)
    md("""
Three fates of one hunger, each named by the same primitive: **kept fed** (Ink's
reading — the loop opens), **wiped** (Blade's rank — the loop never opens), and
**will not feed** (Sound's boat — a longing left standing open). The Ink/Blade
contrast is the novel's thesis, and the sift states it outright: *the same want
that starves another self is, in this one, simply fed.*

### 5.2  `tended_by` — co-regulation, presence rather than argument

`tended_by(other, calms=)` with `steadies()` on the other models the difference
between arguing someone out of a feeling and sitting beside them until it eases.
It turns down the *trust* placed in a distress signal while a steady other is
present — without touching the belief. The tended one still sees what they see;
they are simply no longer alone with it. This is Topman, whose grief floods, and
Rover, who does not argue — he arrives, and stays.
""")
    py(u.build_combs)
    md("""
Watch the dashboard: the grief fires while Topman is alone, and stops the moment
Rover's presence comes into reach.
""")
    code(dashboard(u.build_combs(), width=78))
    md("""
The finding that names it is **held in the dark**:
""")
    code(findings(u.build_combs()))
    md("""
The crucial detail is in the numbers: the alarm's precision falls from high to the
floor and *stays* there, while the thing it senses does **not** go quiet. The
grief's cause never changed; only the trust placed in it did. That is the formal
signature of comfort as opposed to persuasion — and the reason `held in the dark`
is a different finding from a fear that was simply reasoned away.

### 5.3  `holds_with_others` — confidence as belief about other people's belief

`holds_with_others(name, field_tag=)` models a belief whose whole strength is that
everyone else is seen to hold it. Its conviction reads a shared *field* — how much
of the group is still holding — via a small core builtin, `field(tag)`, that
averages a named channel across the whole cast. While the field is full the belief
is unshakeable; when it thins past a tipping point, each holder lets go, which
thins the field further, and the whole thing collapses far faster than any
evidence could move it.

This is the run on the bank at Greywater. Five creditors hold war-paper "sound"
only because the others do. One of them, Venn, actually *reads the paper* — an
appraisal that checks and updates — and when the arithmetic comes up rotten his
own reading (not any outside shock) tips him out of the belief. Quill reads the
same rot and holds anyway, because knowing is not what moves a market. Then
confidence, which stood for days against the truth, cannot stand one hour against
the sight of one man acting on it.
""")
    py(u.build_greywater)
    md("""
The findings are the whole chapter in three lines — the man who counts, the man
who knows and waits, and the cascade they produce:
""")
    code(findings(u.build_greywater()))
    md("""
**the run** is the cascade itself: *N holders kept it aloft… and then let go
together… each one going the moment it saw the others go.* The two confabulations
are the human ends of it — Venn's foreboding as he reads, and Quill's *I know. I
can read. And I am so tired* as he holds a paper he already knows is rotten. To
see the collapse as a shape, the holdings sit flat for four beats and then drop to
zero within two: nothing, nothing, and then everything at once.

### 5.4  `hollowed` — the subtracted self

The eighth temperament, `hollowed`, sets both dials near the floor: little of the
world lands, and little is firmly held. It is the disposition of the one the world
has slowly emptied — a keeper of names worn down to her rounds, a captain in the
mist who can no longer tell the shown from the so. It is distinct from `numb`
(which still holds a prior); a hollowed self holds almost nothing, so it neither
floods nor defends — it simply thins. Reach for it exactly as any other
temperament: `story.character("Ita", temperament=hollowed)`.

### 5.5  `wounded_by` / `believes` / `needs` — the wound, the lie, and the arc

The deepest layer of character, and the one the craft of fiction is most explicit
about (Truby's *ghost → lie → need*; McKee's "dimension means contradiction"): a
formative **wound** teaches a false **lie** the character adopts to survive it;
the lie generates the conscious **want** while defending against a buried
**need**; and the story is the collision between them. Getting the want never
heals the character — only *seeing the lie* does, and whether they see it is the
**arc**.

SOMA models this on its own predictive-processing machinery. The lie is a
high-conviction loop that reads the very evidence that would disconfirm it and,
because conviction outranks that evidence, **suppresses** it — which is exactly
the mechanism of self-deception. What decides the arc is a core primitive,
`overwhelm`: the weight of the suppressed evidence accumulates, and if it crosses
a threshold the belief can no longer hold and is forced to perceive — a
mechanistic **self-revelation**.

The threshold is not a number you have to guess. By default (`breakable=True`)
the lie breaks **automatically**, and *when* it breaks is derived from the belief's
own strengths: the accumulated disconfirming surprise has to exceed roughly the
belief's **conviction** divided by how much it **trusts that evidence**. So a lie
held harder resists longer, a lie that distrusts its evidence resists longer, and
— because each suppression *hardens* the belief (`learn`) — a lie that has been
denied for a long time is harder to break than a fresh one, exactly as entrenched
convictions are in life. You set how strongly the lie is held; the moment of
self-revelation *emerges*.

Here is the same character wired two ways — the only difference is how hard the lie
is held:

```python
from soma.narrative import Story, volatile

def arc(conviction, breakable=True):
    s = Story("arc", span="18s", step="1s", about="a lie and its arc")
    b = s.character("B", temperament=volatile)
    b.wounded_by("named the surplus as a boy", teaches="only-rank")
    b.believes("only-rank",
               claim="If I'm not ranked above them, I'm the surplus again.",
               disconfirmed_by="equal_regard", feeling="worthlessness",
               harms="others", conviction=conviction, breakable=breakable,
               says="Some of us need there to be an upstairs.")
    b.needs("to-matter-as-an-equal", opposes="only-rank",
            feeling="worthlessness", fed_feeling="belonging")
    for t, v in [("3s", 6), ("6s", 7), ("9s", 8), ("12s", 9), ("15s", 9), ("17s", 9)]:
        s.at(t, b.hears("equal_regard", v))   # the fleet's equal regard, escalating
    return s
```

Held softly (`conviction=0.7`), the evidence of equal regard overwhelms the lie
early — the **positive arc**, seen and the need met:
""")
    from soma.narrative import Story as _Story, volatile as _vol

    def _arc(conviction, breakable=True):
        s = _Story("arc", span="18s", step="1s", about="a lie and its arc")
        b = s.character("B", temperament=_vol)
        b.wounded_by("named the surplus as a boy", teaches="only-rank")
        b.believes("only-rank",
                   claim="If I'm not ranked above them, I'm the surplus again.",
                   disconfirmed_by="equal_regard", feeling="worthlessness",
                   harms="others", conviction=conviction, breakable=breakable,
                   says="Some of us need there to be an upstairs.")
        b.needs("to-matter-as-an-equal", opposes="only-rank",
                feeling="worthlessness", fed_feeling="belonging")
        for t, v in [("3s", 6), ("6s", 7), ("9s", 8), ("12s", 9), ("15s", 9),
                     ("17s", 9)]:
            s.at(t, b.hears("equal_regard", v))
        return s

    import textwrap as _tw

    def _arc_findings(story, keep):
        return "\n".join(
            _tw.fill(f"[{f.pattern}] {f.text}", width=78, subsequent_indent="    ")
            for f in story.sift() if f.pattern in keep)

    code(_arc_findings(_arc(0.7),
         {"the lie seen", "the need met"}))
    md("""
Held hard enough (`breakable=None`), the same evidence never breaks it: the lie
suppresses it to the end and only hardens — the **negative, tragic arc**, the self
who meets the truth and doubles down, and the need that never gets met:
""")
    code(_arc_findings(_arc(0.85, breakable=None),
         {"the lie kept", "a need the want never feeds"}))
    md("""
Conviction is the dial that separates the novel's own cast. **Blade**
(`the_unmooring.py ring`) runs the unbreakable lie — *if I'm not ranked above them
I'm the surplus again* — and takes the ring's ladder; his need to matter as an
equal aches to the end and is never met. **Ink** (`fleet`) and the **Coat** hold
breakable versions of the same wound and are *seen*: Ink's lie that he matters only
as the indispensable hand is overwhelmed at the founding (he refuses the pen), and
the Coat's that he is only the house's number breaks at the gate, when his own
unbought acts finally outweigh it. The **Provost** (`selm`) holds his lie *hardest*
of the four (the highest conviction — thirty years of doctrine), so even under the
true sums held up to his face it resists the longest and breaks only at the very
last: the self-revelation that comes too late to undo anything, which is its own
kind of tragedy. None of those four moments is a hand-set number; each falls out
of how hard the lie is held against how strong the evidence gets. Run `python3
examples/narrative/the_unmooring.py ring --character` and `fleet --character` to
see the arcs read straight off the record.
""")


def _section_prediction(u):
    md("""---

### 5.6  Prediction — from modelling a character to forecasting one

Everything so far *models* a character: you specify the pieces and SOMA computes
what follows. A stronger test of a character library is whether it makes **positive
predictions** — whether it can tell you something you did not put in. Cognitive
science draws exactly this line between a *simulation* (which replays its inputs)
and a *prediction* (which must generate an effect under conditions it was never
given, and can therefore be wrong). Two of the library's tools cross it.

**Predict the lie from the wound.** Instead of stating a character's lie, you can
give only the wound — an unmet core need — and how they cope with it, and let the
library forecast the belief. The mapping is schema therapy's: an unmet need becomes
a core self-belief, and a coping style (surrender, avoidance, overcompensation)
turns it into a characteristic lie, want, and behaviour. The prediction is that
*the same wound, coped three ways, is three different people*:
""")
    from soma.narrative import predict_lie as _pl
    rows = []
    for coping in ("surrender", "avoidance", "overcompensation"):
        p = _pl("worth", coping)
        rows.append(f"{coping:17}  \"{p.claim}\"\n"
                    f"{'':19}wants {p.want}; harms {p.harms}")
    code("the wound: an unmet need for worth (Defectiveness / Shame)\n\n"
         + "\n".join(rows))
    md("""
The overcompensation branch is, word for word, the lie the novel gives Blade — so
`adopts("worth", "overcompensation", ...)` rebuilds his tragic arc from the wound
alone, and the surrender and avoidance branches predict the *unwritten* brothers he
might have been. That is a positive prediction: structure derived, not asserted.

**Forecast a response the author never wrote.** Given a finished character,
`predict()` runs the same machinery on a situation that is *not* in the timeline
and reports what the character does with it — suppress it, take it in, or break.
This is the counterfactual a novelist runs in their head when a character starts to
feel real (*"what would she do if…"*); here it is falsifiable, because the model
must actually produce the effect:
""")
    out = []
    out.append(str(u.build_ring().predict("Blade", {"equal_regard": 9})))
    out.append("")
    out.append(str(u.build().predict("Ink", {"kept_for_nothing": 9})))
    code("\n".join(out))
    md("""
Blade *suppresses* even full equal regard; Ink, shown he is kept for nothing,
*breaks*. The library tells the two apart on input neither was scripted to meet —
which is the whole difference between describing a character and predicting one.
And the prediction can be made sharp: `tipping_point()` returns the least evidence
that turns each lie —
""")
    tps = []
    for who, story, ch in [("Ink", u.build(), "kept_for_nothing"),
                           ("Selm", u.build_selm(), "the_margin"),
                           ("Blade", u.build_ring(), "equal_regard")]:
        tp = story.tipping_point(who, ch)
        at = tp["breaks_at"]
        tps.append(f"{who:6} on '{ch}': "
                   + (f"breaks once evidence >= {at}" if at is not None
                      else "never breaks in [0, 9] — the lie is kept"))
    code("\n".join(tps))
    md("""
Selm's doctrine, held hardest of the cast, needs the strongest evidence before it
turns; Blade's never turns at all. Neither number was written down anywhere — both
are forecasts the model stands behind, and either could be shown wrong by running
it. That is what it means for the library to predict rather than merely model.
""")


def _section_closing():
    md("""---

## 6. The five views

Every simulation can be looked at five ways. Use whichever fits the question.

| View | How | What it gives you |
|------|-----|-------------------|
| **Dashboard** | `story.run()` / `soma run` | Body channels, narrator-vs-truth, mood, findings, and a trace — everything at once |
| **Sift** | `story.sift()` / `soma sift` | Just the storyful findings, ranked — the fastest read |
| **Portrait** | `story.characterize()` / `--character` | *Who this person is*, synthesized — disposition, wants, the value they break, the feeling they defend against, the selves they are with each person |
| **Prose** | `story.prose()` / `soma prose` | Free-indirect prose, each sentence a rendered event |
| **Trace** | `soma trace` | The complete event log, nothing curated |

A sixth tool is not a view but an experiment: **`story.perturb("dial=value")`**
changes one number, re-runs, and diffs the findings, so you can ask whether a
mechanism is load-bearing. If a finding *vanishes* when you sever a coupling or
flatten a learning rate, that mechanism was carrying the story — as we saw prove
the inheritance in `the_house` and the structural self-deception in
`the_negotiator`.

---

## 7. The vocabulary, in one place

Everything in this tutorial is built from a small set of verbs on a `Character`.
Roughly from simple to deep:

- `senses(channel)` / `has_body_signal(channel)` — a channel onto the world, or the body
- `appraises(channel, as_threat=, drives=, feeling=, when=, updates=, stops_seeing=, effortful=, shows_on=, fades_to=, ...)` — a loop that reads a channel and reacts
- `feels(quale, from_body=)` — read a feeling off the body
- `narrates(voice=/downplaying=)` — the confabulating self
- `reads(other, surface=, gain=, lag=)` — a coupling: read another's surface
- `has_mood(name, fed_by=, decay=)` — a slow variable that outlasts a feeling
- `learns(rate)` — make appraisals harden with use
- `remembers(name, cued_by=, evokes=)` — a somatic memory / flashback
- `dissociates_when(appraisal=, exceeds=, repair_after=)` — a supervisor that detaches under overload
- `has_attention(capacity=)` + `effortful=True` — a finite spotlight that deliberate loops spend
- `wants(channel)` / `fears(channel)` — drives; both on one channel = ambivalence
- `values(name, says=, betrayed_when=)` — a principle, and the bodily condition of its breach
- `part(name, role=, reacts_to=, feeling=, salience=)` — an internal part that bids for consciousness
- `with_person(other, feeling=, precision=, conviction=)` — a different self for a specific person
- `craves(name, fed_by=, feeling=, erased=)` — a hunger the world can feed and wipe (three fates: fed, wiped, unfed)
- `tended_by(other, calms=)` / `steadies()` / `present()` — co-regulation: presence lowers a distress's precision, not its belief
- `holds_with_others(name, field_tag=, shocked_at=)` — confidence as belief about other people's belief, and its cascade
- `wounded_by(ghost, teaches=, cued_by=, evokes=)` — the formative wound (the Ghost), and the lie it taught
- `believes(lie, claim=, disconfirmed_by=, feeling=, harms=, conviction=, breakable=)` — the Lie: a belief that suppresses its own disconfirming evidence and either breaks (a self-revelation, whose moment `breakable=True` derives automatically from conviction vs. evidence) or, held hard enough (`breakable=None`), only hardens
- `needs(truth, opposes=, feeling=, fed_feeling=)` — the Need: the salve to the lie, not fed by the want, met only when the lie is seen
- `adopts(unmet, coping, disconfirmed_by=)` — *predict* the lie from the wound: an unmet need + a coping style (surrender / avoidance / overcompensation) forecasts the belief, want, and its grip (schema therapy)
- `predict(who, {channel: value})` — forecast a character's response to a situation never scripted (suppress / take-in / break); `tipping_point(who, channel)` gives the least evidence that turns the lie
- `predict_lie(unmet, coping)` (module-level) — inspect the predicted lie for any wound + coping, without building a character

The eight **temperaments** (each a preset of the two dials, some with a learning
rate): `anxious`, `stoic`, `trusting`, `guarded`, `volatile`, `numb`, `tender`,
`hollowed`. Override any single dial per loop with `precision=`, `conviction=`,
`learn=`.

The **sift patterns** the WINNOW-S panel and `story.sift()` report include:
*retained residual*, *confabulation gap* (graded, and it names the denied
feeling), *precision pathology*, *delight in error*, *a mood that sours/lifts*, *a
turn in how they meet the world*, *body remembers alone*, *rupture and repair*,
*attention starved*, *never ignited*, *the thing they both want and fear*
(ambivalence), *the value the body broke*, *the feeling the whole self defends
against*, *the person they became*, *a hunger the world keeps wiping / keeps fed /
will not feed*, *held in the dark*, *the run*, *the lie seen* / *the lie kept*
(the arc), and *the need met* / *a need the want never feeds* (the want/need
collision).

And on the `Story`: `character` and `scene` (declare people and label spans of
time), `at` (place an event at a time) and `over` (spread an `arc` shape across
the timeline), `run` / `sift` / `characterize` / `prose` (the views), `perturb`
(the change-one-dial experiment), and `source` (dump the generated SOMA).

---

## 8. Why this yields novelistic insight

The recurring move in every example is the same: **two mechanisms that can
disagree.** The narrator says one thing; the body's record says another. A value
is held in words and broken in the flesh. A part bids for awareness and is never
heard. A hunger is fed by one supply and wiped by another. A person is one self
here and another there.

None of those gaps is authored as a conclusion. You write the *parts* — the dials,
the couplings, the drives, the hungers — and the gap emerges from running them;
then the sift finds it and names it. That is why the output can *surprise* the
author: you did not write *she defends against terror*; you wrote a loud protector
and a quiet child, and the sift discovered which feeling never got through. You
did not write *the same hunger saves one brother and ruins the other*; you set one
`erased=0.0` and the other `erased=0.9`, and the contrast fell out.

Characterization, in a novel, is precisely this: not what a person says about
themselves, but the distance between that and what they do. SOMA makes that
distance a measurable, inspectable thing — and hands it back to you as a
dashboard, a portrait, a prose passage, and a ranked list of the moments that
matter.

Start with `bad_news`, change a temperament, and watch the findings move. Then
open `the_unmooring` and watch a whole cast assemble from the same handful of
verbs. That is the whole method.
""")


def _trace_full(story) -> str:
    """Render the complete chronicle the way the `trace` view does, tightened to
    stay near the page width. Every event is present; nothing is elided."""
    lines = []
    for e in story.result().chronicle:
        d = " ".join(f"{k}={v}" for k, v in e.detail.items())
        who = e.who if len(e.who) <= 16 else e.who[:15] + "…"
        lines.append(f"{e.t:>5.1f} {e.kind:<8} {who:<16} {d}")
    return "\n".join(lines)


if __name__ == "__main__":
    main()
