"""
Tests for the browser bridge's library mode -- web_bridge.run_python, which
execs user Python that drives soma.narrative and captures its output. These
guard the dual-mode playground: SOMA source via run_command, library Python via
run_python, and the bridge between them (hand-written SOMA run through the
library; library builds printing the SOMA they compile to).
"""
import re
import web_bridge


def _plain(s):
    """strip ANSI color for assertions."""
    return re.sub(r"\x1b\[[0-9;]*m", "", s)


class TestRunPython:
    def test_simple_print_is_captured(self):
        out = _plain(web_bridge.run_python("print('hello from library')"))
        assert "hello from library" in out

    def test_narrative_library_is_preloaded(self):
        """Short snippets need no imports: the whole narrative package is in the
        namespace."""
        code = ("s = Story('t', span='6s', step='1s')\n"
                "c = s.character('X', temperament=tender)\n"
                "c.senses('f')\n"
                "c.appraises('f', feeling='delight', when='f > 3')\n"
                "s.at('2s', c.hears('f', 7))\n"
                "print('emits', sum(1 for e in s.result().chronicle "
                "if e.kind=='emit'))")
        out = _plain(web_bridge.run_python(code))
        assert "emits" in out and "Error" not in out

    def test_explicit_import_still_works(self):
        code = ("from soma.narrative import Story, stoic\n"
                "print(type(Story).__name__)")
        out = _plain(web_bridge.run_python(code))
        assert "Error" not in out

    def test_predictive_method_runs(self):
        code = (
            "s = Story('ss', span='24s', step='1s', about='separation')\n"
            "c = s.character('Noa', temperament=stoic)\n"
            "c.attaches('avoidant', to='mother')\n"
            "print(strange_situation(s, c).classification)")
        out = _plain(web_bridge.run_python(code))
        assert "avoidant" in out

    def test_handwritten_soma_through_the_library(self):
        """The bridge direction: write SOMA text, run it via run_source."""
        code = (
            "src = '''sim { duration: 4s dt: 1s }\n"
            "body B @cardiac { intero h : H baseline 70 }\n"
            "stimulus h { at 2s: 120 }\n"
            "loop l @cardiac { prior: predict(70) sense: h precision: 0.9 "
            "conviction: 0.3 act { emit feel(surprise) } }'''\n"
            "r = run_source(src, title='hand')\n"
            "print('surprise' in [str(e.detail.get('quale','')) "
            "for e in r.chronicle if e.kind=='emit'][0])")
        out = _plain(web_bridge.run_python(code))
        assert "True" in out

    def test_library_build_prints_generated_soma(self):
        """The other direction: build with the library, read the SOMA."""
        code = ("s = Story('g', span='6s', step='1s')\n"
                "c = s.character('C', temperament=tender)\n"
                "c.senses('face')\n"
                "c.appraises('face', feeling='delight', when='face > 3')\n"
                "print(s.source())")
        out = _plain(web_bridge.run_python(code))
        assert "generated by soma.narrative" in out
        assert "loop" in out

    def test_error_is_a_red_banner_not_a_crash(self):
        out = _plain(web_bridge.run_python("print(does_not_exist)"))
        assert "NameError" in out
        # partial output before the error is preserved
        out2 = _plain(web_bridge.run_python("print('before')\nprint(boom)"))
        assert "before" in out2 and "NameError" in out2

    def test_traceback_does_not_leak_the_bridge_frame(self):
        """The user should see only their own frames, never the bridge's
        exec(compile(...)) line or web_bridge.py internals."""
        out = _plain(web_bridge.run_python(
            "def a(): return b()\ndef b(): return 1/0\nprint(a())"))
        assert "exec(compile" not in out
        assert "web_bridge" not in out
        assert '<your code>' in out       # user frames ARE shown
        assert "ZeroDivisionError" in out

    def test_syntax_error_is_reported(self):
        out = _plain(web_bridge.run_python("def oops(:\n  pass"))
        assert "SyntaxError" in out

    def test_empty_output_gets_a_hint(self):
        out = _plain(web_bridge.run_python("x = 2 + 2"))
        assert "printed nothing" in out


class TestRunCommandStillWorks:
    """The SOMA mode must be unaffected by the addition of library mode."""

    SRC = ("sim { duration: 4s dt: 1s }\n"
           "body B @cardiac { intero h : H baseline 70 }\n"
           "stimulus h { at 2s: 120 }\n"
           "loop l @cardiac { prior: predict(70) sense: h precision: 0.9 "
           "conviction: 0.3 act { emit feel(surprise) } }")

    def test_run_command_renders(self):
        out = _plain(web_bridge.run_command("run", self.SRC, "t",
                                            rows=10, width=72))
        assert "SOMA" in out and "surprise" in out

    def test_check_command(self):
        out = _plain(web_bridge.run_command("check", self.SRC, "t", width=72))
        assert "checks clean" in out
