"""
soma.prose -- the novelist's output.

The panels tell you *what the model did*. This module tells you *what happened
to a person*. It reads the Chronicle scene by scene and renders free indirect
discourse: third-person narration that leans into a character's own idiom,
placing what the body did beside what the narrator claimed, and letting the gap
between them do the work.

Nothing here is generated by a language model. Every clause is a rendering of a
specific logged event: a drive, a spend, an ignition that failed, a quale the
narrator never saw. The prose is a *view* on the trace, which is why it can be
trusted as material -- and why a novelist should throw most of it away and keep
the one sentence that surprised them.
"""

from __future__ import annotations

# ---- lexicons: how an event reads on the page ----
FEEL_PHRASE = {
    "dread": "something went wrong low in {poss} stomach",
    "terror": "{subj} went cold all the way to {poss} hands",
    "pain": "the pain arrived, familiar, punctual",
    "grief": "the missing came back the way weather comes back",
    "reaching": "{poss} body reached for what was not there",
    "shame": "{poss} face was hot before {subj} knew why",
    "despair": "the floor of {obj} gave a little",
    "numbness": "{subj} felt nothing, which was itself a kind of information",
    "delight_at_error": "{subj} was wrong again, and glad of it",
    "delight": "something in {obj} lifted",
    "warmth": "{subj} was, briefly, unguarded",
    "love": "{subj} could have watched all evening",
    "contempt": "{subj} had seen it all before, and it tired {obj}",
    "recognition": "{subj} knew the smell before {subj} named it",
    "hope": "{subj} let {refl} want something",
    "calm": "{poss} breathing found its floor",
    "relief": "the held thing in {poss} chest let go",
    "anguish": "{subj} had no name for it and no place to put it",
    "panic": "the room got very bright and very far away",
    "worthlessness": "{subj} was, {subj} understood, entirely surplus",
    "pride": "for one breath {subj} was more than the others, and knew it",
}

PRONOUNS = {
    "she": dict(subj="she", obj="her", poss="her", refl="herself"),
    "he": dict(subj="he", obj="him", poss="his", refl="himself"),
    "they": dict(subj="they", obj="them", poss="their", refl="themselves"),
}


def _p(who, gender="they"):
    d = dict(PRONOUNS.get(gender, PRONOUNS["they"]))
    d["name"] = who
    # singular "they" still takes plural agreement ("they were"), so verbs are
    # looked up, never conjugated inline.
    d["was"] = "were" if d["subj"] == "they" else "was"
    d["were"] = "were"
    return d


def _fmt_t(t):
    if t < 90:
        return f"{t:.0f} seconds in"
    if t < 5400:
        return f"{t/60:.0f} minutes in"
    if t < 172800:
        return f"{t/3600:.0f} hours in"
    if t < 3.15e7:
        return f"{t/86400:.0f} days in"
    return f"{t/3.15e7:.0f} years in"


def _gender_for(who, genders):
    if who in genders:
        return genders[who]
    return genders.get("__default__", "they")


def _owner_of(name):
    return name.split(".")[0] if "." in name else None


def _short(name):
    return name.split(".")[-1]


def _scenes(prog, chron):
    """Partition the Chronicle into scenes; everything outside any declared
    scene falls into a final unnamed beat."""
    if not prog.scenes:
        return [(None, list(chron))]
    out = []
    for sc in prog.scenes:
        evs = [e for e in chron if sc.t0 <= e.t <= sc.t1]
        out.append((sc.title, evs))
    covered = set()
    for sc in prog.scenes:
        covered |= {id(e) for e in chron if sc.t0 <= e.t <= sc.t1}
    rest = [e for e in chron if id(e) not in covered]
    if rest:
        out.append((None, rest))
    return out


def _quale(e):
    q = e.detail.get("quale", "")
    return q[7:-1] if q.startswith("Qualia<") else q


def render_scene(title, events, genders, width=76, said=None):
    """One beat, as prose.

    `said` is threaded across scenes, so each beat reports only what is new.
    A feeling that has already been named is not named again -- which is both
    better prose and a truer account of experience, where the second time is
    never the first time."""
    lines = []
    if title:
        lines.append(f"— {title} —")
        lines.append("")

    said = said if said is not None else set()
    body = []

    for e in events:
        who = _owner_of(e.who) or e.who
        g = _p(who, _gender_for(who, genders))

        if e.kind in ("emit", "somatic"):
            q = _quale(e)
            key = (who, q, e.kind)
            if key in said:
                continue
            said.add(key)
            phrase = FEEL_PHRASE.get(q)
            if phrase:
                s = phrase.format(**g)
                if e.kind == "somatic":
                    s += ", and nothing in her memory would say why" \
                        if g["subj"] == "she" else \
                        ", and nothing in his memory would say why" \
                        if g["subj"] == "he" else \
                        ", and nothing in their memory would say why"
                body.append(_cap(s) + ".")
            else:
                body.append(f"{_cap(g['subj'])} felt {q}.")

        elif e.kind == "narrate":
            quote = e.detail.get("quote", "")
            gap = e.detail.get("gap", 0)
            if (who, quote) in said:
                continue
            said.add((who, quote))
            if gap >= 0.9:
                body.append(f'"{quote}" {g["subj"].capitalize()} said it as if '
                            f"{g['subj']} had known all along.")
            elif gap >= 0.5:
                body.append(f'"{quote}" It was not true, and {g["subj"]} did not '
                            f"know it was not true.")
            else:
                body.append(f'"{quote}"')

        elif e.kind == "budget" and ("budget", who) not in said:
            said.add(("budget", who))
            body.append(f"There was nothing left to spend. "
                        f"{_cap(g['subj'])} spent it anyway, and it cost {g['obj']}.")

        elif e.kind == "crash" and ("crash", who) not in said:
            said.add(("crash", who))
            body.append(f"Then {g['subj']} {g['was']} somewhere above it, watching "
                        f"{g['refl']} be a person in a room.")

        elif e.kind == "repair" and ("repair", who) not in said:
            said.add(("repair", who))
            body.append("Coming back was not a flood. It was a series of small "
                        "permissions.")

        elif e.kind == "conflict" and ("conflict", e.who) not in said:
            said.add(("conflict", e.who))
            part = _short(e.detail.get("pair", "body")).replace("_", " ")
            if part in ("left arm", "right arm", "hand", "leg"):
                body.append(f"The {part} that reached and the {part} {g['subj']} "
                            f"could picture were not the same {part}.")
            else:
                body.append(f"The {part} the room could see and the {part} "
                            f"{g['subj']} could picture were not the same {part}.")

        elif e.kind == "ownership" and ("own", e.who, e.detail.get("state")) not in said:
            said.add(("own", e.who, e.detail.get("state")))
            st = e.detail.get("state")
            if st == "disowned":
                body.append(f"It stopped being {g['poss']} and became a thing "
                            f"on the table {g['subj']} could see moving.")
            elif ("own", e.who, "disowned") in said:
                body.append(f"It became {g['poss']} again.")
            else:
                body.append(f"The thing on the table became {g['poss']} hand. "
                            f"{_cap(g['subj'])} could feel the brush land on it.")

        elif e.kind == "ignite" and ("ig", e.detail.get("content")) not in said:
            said.add(("ig", e.detail.get("content")))
            thought = _humanize(_short(e.detail.get("content", "it")))
            body.append(f"{_cap(thought)} — that was the thought that arrived, "
                        f"and it arrived whole.")

        elif e.kind == "couple" and ("couple", e.who, e.detail.get("to")) not in said:
            said.add(("couple", e.who, e.detail.get("to")))
            src_who = _owner_of(e.who) or e.who
            dst_who = _owner_of(e.detail.get("to", "")) or ""
            surface = _short(e.who).replace("_", " ")
            if src_who != dst_who and dst_who:
                when = _lag_phrase(e.detail.get("lag", 0) or 0)
                body.append(f"{dst_who} was reading {src_who}'s {surface}, {when}.")

        elif e.kind == "ignore" and ("ignore", e.who) not in said:
            said.add(("ignore", e.who))
            body.append(f"{_cap(g['subj'])} had stopped listening, and did not "
                        f"experience this as having stopped listening.")

        elif e.kind == "starved" and ("starved", e.who) not in said:
            said.add(("starved", e.who))
            body.append(f"There was not enough of {g['obj']} left to think with.")

        elif e.kind == "learn" and ("learn", e.who) not in said:
            said.add(("learn", e.who))
            body.append("The belief was getting easier to hold. That was the "
                        "problem with it.")

        elif e.kind == "rebus" and ("rebus",) not in said:
            said.add(("rebus",))
            body.append("And then, without anything in the room changing, "
                        "everything in the room became negotiable.")

    if not body:
        # A scene may contain no *new* event types and still not be empty: a
        # condition established years ago can simply persist. Rather than report
        # "nothing happened," name what is still true.
        ongoing = _ongoing(events, genders)
        if ongoing:
            body.append(ongoing)
        else:
            body.append("Nothing happened that anyone would later remember.")
            if title:
                body[-1] = "Nothing new happened. That was the whole of it."

    lines.extend(_wrap(" ".join(body), width))
    lines.append("")
    return lines


def _ongoing(events, genders):
    """Name a condition that is still true in a scene that reports no new event.

    A body that has been overriding safety for sixteen years is not doing
    "nothing"; it is doing the same thing, still. This gives the quiet years
    their weight without pretending something new occurred."""
    kinds = {}
    for e in events:
        kinds.setdefault(e.kind, []).append(e)
    who = None
    for e in events:
        who = _owner_of(e.who) or e.who
        if who:
            break
    g = _p(who, _gender_for(who, genders)) if who else _p("they")
    # is this a long life or a short scene? choose language to match.
    span = (events[-1].t - events[0].t) if len(events) > 1 else 0
    long_scale = span > 2.6298e6      # more than a month of simulated time
    interval = "that year" if long_scale else "again and again"
    if "somatic" in kinds:
        return (f"The body went on asking. It asked {len(kinds['somatic'])} times "
                f"{interval}, in the register that keeps no story, and got no answer.")
    if "ignore" in kinds:
        return (f"{_cap(g['subj'])} went on overriding what the room was telling "
                f"{g['obj']}, and went on not knowing {g['subj']} did.")
    if "emit" in kinds:
        q = _quale(kinds["emit"][0])
        return f"The {q} was still there. It had stopped being news."
    if "ignite" in kinds or "broadcast" in kinds:
        return (f"The two halves of {g['obj']} went on doing what each could see, "
                f"and neither could say what the other was doing.")
    if "drive" in kinds or "spend" in kinds:
        if long_scale:
            return f"{_cap(g['subj'])} held the same posture {g['subj']} had held for years."
        return f"{_cap(g['subj'])} did it again, and then again."
    return ""


def _lag_phrase(lag):
    """How late one person's news of another arrives, in English."""
    if lag <= 0:
        return "almost at once"
    if lag < 1:
        return "a half-second late"
    for size, one, many in ((60, "a second", "seconds"),
                            (3600, "a minute", "minutes"),
                            (86400, "an hour", "hours"),
                            (604800, "a day", "days"),
                            (2.6298e6, "a week", "weeks"),
                            (3.1536e7, "a month", "months"),
                            (float("inf"), "a year", "years")):
        if lag < size:
            break
    scale = {"seconds": 1, "minutes": 60, "hours": 3600, "days": 86400,
             "weeks": 604800, "months": 2.6298e6, "years": 3.1536e7}[many]
    n = lag / scale
    return f"{one} late" if abs(n - 1) < 0.05 else f"{n:.0f} {many} late"


def _humanize(label):
    """`he_thinks_i_am_ridiculous` -> `he thinks I am ridiculous`."""
    words = label.replace("(", " ").replace(")", "").replace("_", " ").split()
    return " ".join("I" if w == "i" else w for w in words)


def _cap(s):
    return s[0].upper() + s[1:] if s else s


def _wrap(s, w):
    words, out, cur = s.split(), [], ""
    for wd in words:
        if len(cur) + len(wd) + 1 > w:
            out.append(cur); cur = wd
        else:
            cur = (cur + " " + wd).strip()
    if cur:
        out.append(cur)
    return out


def render(result, genders=None, width=76):
    """Render the whole run as prose, scene by scene."""
    genders = genders or {}
    prog = result.program
    # In a single-character sim, events are logged under loop or memory names
    # rather than a character name, so `--gender Wren:he` would never match. Bind
    # a default gender to the sole subject, so the pronouns still land.
    if len(prog.characters) <= 1 and genders:
        subject = prog.characters[0] if prog.characters else (
            prog.bodies[0].name if prog.bodies else None)
        the_gender = None
        if subject and subject in genders:
            the_gender = genders[subject]
        elif len(genders) == 1:
            the_gender = next(iter(genders.values()))
        if the_gender:
            genders = dict(genders)
            genders["__default__"] = the_gender
    out = [f"{prog.title.replace('_',' ').upper()}", ""]
    said = set()
    for title, events in _scenes(prog, result.chronicle):
        out.extend(render_scene(title, events, genders, width, said=said))
    out.append("")
    out.extend(_wrap(
        "(Every sentence above is a rendering of a logged event. "
        "The gap between what was said and what the body did is the "
        "only thing here that was not authored.)", width))
    return "\n".join(out)
