"""
The compiler: narrative intent -> SOMA source text.

Given a fully-built Story, emit a `.soma` program that the base parser accepts.
The output is deliberately *readable* -- a human can inspect exactly what the
high-level calls produced, which keeps the abstraction honest and debuggable.
"""
from __future__ import annotations
import re


def _ident(s: str) -> str:
    """A safe SOMA identifier from a human name (hyphens, spaces -> underscore)."""
    return re.sub(r"\W+", "_", str(s)).strip("_")


# feelings the base checker treats as distress -> require @consent
_DISTRESS = {"dread", "pain", "despair", "grief", "terror", "panic", "shame",
             "anguish", "reaching", "numbness", "contempt",
             "desolation", "foreboding", "apprehension", "self_betrayal",
             "worthlessness"}


class Compiler:
    def __init__(self, story):
        self.s = story
        self.lines = []

    def emit(self, *ls):
        self.lines.extend(ls)

    def compile(self):
        self._header()
        self._sim()
        self._scenes()
        multi = len(self.s.characters) > 1
        for c in self.s.characters:
            if multi:
                self._character_scoped(c)
            else:
                self._character_flat(c)
        self._stimuli()
        self._couples()
        return "\n".join(self.lines) + "\n"

    # ---- preamble ----------------------------------------------------------
    def _header(self):
        self.emit(f"// {self.s.title} -- generated by soma.narrative",
                  "// Every construct below was produced from a high-level "
                  "narrative description;",
                  "// it is ordinary SOMA and can be edited, run, sifted, "
                  "prosed, and perturbed.")
        if self._needs_consent():
            note = self.s.about or "simulates distress"
            self.emit(f'@consent("{note}")')
        self.emit("")

    def _needs_consent(self):
        for c in self.s.characters:
            for f in c._feelings:
                if f.quale in _DISTRESS:
                    return True
            for a in c._appraisals:
                if a.feeling in _DISTRESS:
                    return True
            for m in c._memories:
                if m.evokes in _DISTRESS:
                    return True
            # a held value emits self_betrayal when violated -- that is distress
            if c._values:
                return True
            for p in c._parts:
                if p.feeling in _DISTRESS:
                    return True
            for r in c._relations:
                if r.feeling in _DISTRESS:
                    return True
            for cr in c._cravings:
                # a hunger that aches when unfed, or that the world keeps wiping,
                # is distress -- the coat, the erased rank, the comb.
                if cr.feeling in _DISTRESS:
                    return True
            # a lie defends against a distressing feeling; a need aches until met
            for l in c._lies:
                if l.feeling in _DISTRESS:
                    return True
            for n in c._needs:
                if n.feeling in _DISTRESS:
                    return True
        return False

    def _sim(self):
        cad = "  cadence: true" if self.s.cadence else ""
        self.emit(f"sim {{ duration: {self.s.span}  dt: {self.s.step}{cad} }}", "")

    def _scenes(self):
        for (title, frm, to) in self.s._scenes:
            self.emit(f'scene "{title}"  from {frm}  to {to}')
        if self.s._scenes:
            self.emit("")

    # ---- one character, no character{} wrapper -----------------------------
    def _character_flat(self, c):
        self._body(c, indent="")
        self._budget(c, indent="")
        self._attention(c, indent="")
        self._workspace(c, indent="")
        self._surface_flows(c, indent="")
        self._craving_flows(c, indent="")
        self._loops(c, indent="")
        self._feeling_loops(c, indent="")
        self._value_loops(c, indent="")
        self._part_loops(c, indent="")
        self._relation_loops(c, indent="")
        self._craving_loops(c, indent="")
        self._confidence_loops(c, indent="")
        self._lie_loops(c, indent="")
        self._need_loops(c, indent="")
        self._steady_drive(c, indent="")
        self._memories(c, indent="")
        self._handlers(c, indent="")
        self._moods(c, indent="")
        self._drives(c, indent="")
        self._narrator(c, indent="")

    # ---- one of many, wrapped in character{} -------------------------------
    def _character_scoped(self, c):
        self.emit(f"character {c.name} {{")
        self._body(c, indent="  ")
        self._attention(c, indent="  ")
        self._workspace(c, indent="  ")
        self._surface_flows(c, indent="  ")
        self._craving_flows(c, indent="  ")
        self._loops(c, indent="  ")
        self._feeling_loops(c, indent="  ")
        self._value_loops(c, indent="  ")
        self._part_loops(c, indent="  ")
        self._relation_loops(c, indent="  ")
        self._craving_loops(c, indent="  ")
        self._confidence_loops(c, indent="  ")
        self._lie_loops(c, indent="  ")
        self._need_loops(c, indent="  ")
        self._steady_drive(c, indent="  ")
        self._memories(c, indent="  ")
        self.emit("}")
        self._budget(c, indent="")
        self._handlers(c, indent="", scoped=c.name)
        self._moods(c, indent="", scoped=c.name)
        self._drives(c, indent="", scoped=c.name)
        self._narrator(c, indent="", scoped=c.name)
        self.emit("")

    # ---- pieces ------------------------------------------------------------
    def _body(self, c, indent):
        if not c._senses:
            c._senses.append(_blank_sense())
        self.emit(f"{indent}body {c.name}_body @{c.clock} {{")
        for s in c._senses:
            self.emit(f"{indent}  {s.modality} {s.channel} : {s.kind} "
                      f"baseline {_num(s.baseline)}")
        self.emit(f"{indent}}}")
        self.emit("")

    def _budget(self, c, indent):
        if c._budget is not None:
            self.emit(f"{indent}resource {c.name}_budget : Affine<Joule> "
                      f"= metabolic_reserve({_num(c._budget)})", "")

    def _attention(self, c, indent):
        if c._attention is not None:
            self.emit(f"{indent}attention {c.name}_spotlight = "
                      f"capacity({_num(c._attention.capacity)})", "")

    def _surface_flows(self, c, indent):
        """A surface that a feeling drives should decay back toward rest, so the
        tell is transient -- a face composes itself again. Emitted as a flow on
        the body clock.

        The time constant must be a few *timesteps* of the story, not a fixed
        number of seconds: on a biography clock (dt = 1 year) a 3-second decay
        would be astronomically stiff and the integrator would diverge. We size
        it from the story's step so the tell fades over ~3 beats on any clock."""
        tau = 3.0 * _dur(self.s.step)
        for surface, rest in c._surface_decays.items():
            self.emit(f"{indent}flow {surface} @{c.clock} {{ dynamics: "
                      f"-({surface} - {_num(rest)}) / {_num(tau)} }}", "")

    def _moods(self, c, indent, scoped=None):
        if not c._moods:
            return
        # Build a map from a quale this character feels to the loop(s) that emit
        # it. A mood must integrate its OWNER's loops, not the bare quale --
        # otherwise, in a multi-character story, one person's dread would deepen
        # another's mood (they share the quale name). The base language lets a
        # mood key on a loop name, so we resolve each source to this character's
        # own emitting loops and, when scoped, qualify them (Ana.feeling_dread).
        quale_to_loops: dict[str, list] = {}
        for a in c._appraisals:
            if a.feeling:
                quale_to_loops.setdefault(a.feeling, []).append(a.name)
        for f in c._feelings:
            quale_to_loops.setdefault(f.quale, []).append(f"feeling_{f.quale}")
        for m in c._moods:
            terms = []
            for (src, w) in m.integrates:
                loops = quale_to_loops.get(src)
                if loops:
                    for ln in loops:
                        full = f"{scoped}.{ln}" if scoped else ln
                        terms.append(f"{full} * {_num(w)}")
                else:
                    # the source is not a quale this character feels; fall back
                    # to the bare name (may be a quale emitted elsewhere by
                    # design, or a typo -- kept permissive, like the base lang).
                    terms.append(f"{src} * {_num(w)}")
            parts = "  ".join(terms)
            self.emit(f"{indent}mood {c.name}_{m.name} : Affect @mood "
                      f"integrates {{ {parts} }} decay {_num(m.decay)}", "")

    def _mode_line(self, c, indent, effortful):
        """Which mode line a loop needs. When the character has an attention
        spotlight, non-effortful loops must be declared `habit` so they run free;
        only effortful ones stay `deliberate` and compete for the spotlight. When
        there is no spotlight, the base-language default is fine and we emit
        nothing."""
        if c._attention is None:
            return ""
        kind = "deliberate" if effortful else "habit"
        return f"\n{indent}  mode:       {kind}"

    def _loops(self, c, indent):
        for a in c._appraisals:
            if a.expects is not None:
                prior = _num(a.expects)
            else:
                prior = _num(c.temp.baseline_expectation) if a.threat else "0"
            learn = f"\n{indent}  learn:      {_num(a.learn)}" if a.learn else ""
            # A loop defaults to `deliberate`, which spends the attention
            # spotlight. Only appraisals the author marked `effortful` should
            # compete for it; everything else must be `habit` (free), or a single
            # spotlight would starve the character's entire mind.
            mode = self._mode_line(c, indent, a.effortful)
            # Co-regulation: if a steady other tends this exact distress loop, its
            # precision becomes an expression that falls as the incoming
            # steadiness rises -- so a present, calm companion turns down the
            # trust placed in the alarm WITHOUT touching the prior. The character
            # still believes what they believe (the belief is the prior, and it
            # is untouched); they are simply no longer flooded, because they are
            # no longer alone with it. Presence, not persuasion.
            prec = _num(a.precision)
            tend = next((t for t in c._tendings if t.calms == a.name), None)
            if tend is not None:
                prec = (f"clamp({_num(a.precision)} - {_num(tend.strength)} "
                        f"* {tend.channel} / 8, 0.05, {_num(a.precision)})")
            self.emit(f"{indent}loop {a.name} @{c.clock} {{",
                      f"{indent}  prior:      predict({prior})",
                      f"{indent}  sense:      {a.sense}",
                      f"{indent}  precision:  {prec}",
                      f"{indent}  conviction: {_num(a.conviction)}{learn}{mode}",
                      f"{indent}  act {{")
            guard = f" when {a.when}" if a.when else ""
            if a.effortful and c._attention is not None:
                # deliberating costs the spotlight; when it is spent, this loop
                # is starved and cannot act -- attention as a scarce resource.
                self.emit(f"{indent}    attend {c.name}_spotlight 1")
            if a.updates:
                self.emit(f"{indent}    update -> revise_my_picture")
            spent_early = False
            if getattr(a, "spend_first", False) and a.feeling and c._budget is not None:
                # a costly reaction whose drive on the body should itself be
                # gated by the budget: spend BEFORE driving, so when the body
                # can no longer fund the surge, the drive does not happen and
                # the vicious cycle starves. (Robinaugh's homeostatic ceiling,
                # as an affine resource rather than a subtracted term.)
                self.emit(f"{indent}    move ! spend({c.name}_budget, "
                          f"{_num(c.temp.feeling_cost)}){guard}")
                spent_early = True
            if a.drives_body:
                # the drive on the body is part of the same reaction as the
                # feeling: if the appraisal only fires under a condition, so does
                # its reach into physiology.
                self.emit(f"{indent}    move ! set({a.drives_body}, "
                          f"{_num(a.drives_to)}){guard}")
            if a.shows_on:
                # the feeling reaches the surface: a tell the world can read
                self.emit(f"{indent}    move ! set({a.shows_on}, "
                          f"{_num(a.shows_value)}){guard}")
            if a.feeling:
                if c._budget is not None and not spent_early:
                    self.emit(f"{indent}    move ! spend({c.name}_budget, "
                              f"{_num(c.temp.feeling_cost)}){guard}")
                self.emit(f"{indent}    emit feel({a.feeling}){guard}")
            if a.stops_seeing:
                # inert until a hardening prior outranks the senses; then the
                # arbitration flips to `act` and this silences the world.
                self.emit(f"{indent}    ignore")
            if not a.drives_body and not a.feeling and not a.updates:
                self.emit(f"{indent}    update -> what_i_make_of_it")
            self.emit(f"{indent}  }}", f"{indent}}}", "")

    def _drives(self, c, indent, scoped=None):
        """Wanting and fearing become allostats -- predictive pulls on a channel
        toward a goal. Two on one channel = ambivalence, and the Chronicle logs
        both pulls every moment, which is how Winnow-S later sees the tension.

        In a multi-character story the body channel is scoped (Immy.closeness),
        so the allostat must regulate the qualified name or it would bind to
        nothing."""
        for d in c._drives:
            chan = f"{scoped}.{d.channel}" if scoped else d.channel
            self.emit(f"{indent}allostat {d.name} {{ regulate: {chan}  "
                      f"setpoint: {_num(d.toward)}  gain: {_num(d.gain)} }}", "")

    def _workspace(self, c, indent):
        """A character with internal parts needs a workspace for them to compete
        in -- Dehaene's global ignition. Only the winning part reaches awareness;
        the rest are felt but never known."""
        if c._parts:
            self.emit(f"{indent}workspace {c.name}_mind {{ ignite at 0.55 }}", "")

    def _part_loops(self, c, indent):
        """Each internal part is a loop that reacts to something and bids for
        consciousness at its salience. A loud protector drowns out a quiet exile:
        the exile's feeling still fires (it is real, and logged) but its bid
        loses the workspace, so it is 'never ignited' -- felt, never known."""
        for p in c._parts:
            pmode = self._mode_line(c, indent, effortful=False)
            safe = p.name.replace("-", "_")
            guard = f" when {p.when}" if p.when else ""
            self.emit(f"{indent}loop part_{safe} @{c.clock} {{",
                      f"{indent}  prior:      predict(0)",
                      f"{indent}  sense:      {p.channel}",
                      f"{indent}  precision:  0.8",
                      f"{indent}  conviction: 0.3{pmode}",
                      f"{indent}  act {{")
            content = safe + "_speaks"
            self.emit(f"{indent}    broadcast {content} salience: {_num(p.salience)}{guard}")
            self.emit(f"{indent}    emit feel({p.feeling}){guard}",
                      f"{indent}  }}", f"{indent}}}", "")

    def _relation_loops(self, c, indent):
        """The relational self: one loop per person this character is *with*,
        each running its own precision and conviction. The same character is a
        different self with each -- open with one, defended with another.

        The loop expects the other absent (a low prior) and feels its feeling
        when their face is present and engaged (the gate), so being *with* that
        person is what brings that self online. Different people, different
        selves, each summoned by presence."""
        for r in c._relations:
            rmode = self._mode_line(c, indent, effortful=False)
            safe = r.other.lower()
            self.emit(f"{indent}loop with_{safe} @{c.clock} {{",
                      f"{indent}  prior:      predict(0)",
                      f"{indent}  sense:      {r.channel}",
                      f"{indent}  precision:  {_num(r.precision)}",
                      f"{indent}  conviction: {_num(r.conviction)}{rmode}",
                      f"{indent}  act {{",
                      f"{indent}    emit feel({r.feeling}) when {r.channel} > 4",
                      f"{indent}  }}", f"{indent}}}", "")

    def _value_loops(self, c, indent):
        """A held value is a loop that watches for its own betrayal. It emits a
        marker feeling when the condition goes true -- the moment the character
        does the thing they'd swear they never would. The narrator (subscribed
        to it) still speaks the value aloud, so the gap is on the page."""
        for v in c._values:
            # a loop that reads the betrayal channel and, when the condition is
            # met, emits a distinctive 'self_betrayal' marker the sifter finds.
            # It runs as habit -- watching your own conscience is not effortful,
            # and it must not be starved by an attention spotlight.
            vmode = self._mode_line(c, indent, effortful=False)
            self.emit(f"{indent}loop upholding_{v.name} @{c.clock} {{",
                      f"{indent}  prior:      predict(0)",
                      f"{indent}  sense:      {v.on_channel}",
                      f"{indent}  precision:  0.9",
                      f"{indent}  conviction: 0.2{vmode}",
                      f"{indent}  act {{",
                      f"{indent}    emit feel(self_betrayal) when {v.betrayed_when}",
                      f"{indent}  }}", f"{indent}}}", "")

    def _craving_flows(self, c, indent):
        """The erasure: each craving's relief channel drains back toward empty,
        at a rate set by `erased`. A high rate is the ring's tide-clean, wiping
        the rank each night; a low rate is an ordinary satisfaction that lasts.
        Sized in timesteps like every other flow, so it works on any clock."""
        step = _dur(self.s.step)
        for cr in c._cravings:
            if cr.erased > 0:
                # tau shrinks as `erased` -> 1 (faster wipe). ~1..6 timesteps.
                tau = max(0.6, (1.2 - min(0.99, cr.erased))) * step * 5.0
                self.emit(f"{indent}flow {cr.relief} @{c.clock} {{ dynamics: "
                          f"-({cr.relief}) / {_num(round(tau, 4))} }}", "")

    def _craving_loops(self, c, indent):
        """A hunger the world feeds and charges for. Two loops:

        * a feeding loop that, while the supply is present, tops the relief up
          (and, if named, emits the *hit* -- what being fed feels like);
        * a hunger loop that emits the ache whenever the relief has drained below
          threshold -- which, if the erasure is fast, is most of the time.

        Together with the erasure flow this is the addiction shape: fed, wiped,
        hungry, fed again -- the loop that never opens (Blade's rank, the coat,
        the comb where wage and want are one substance)."""
        for cr in c._cravings:
            fmode = self._mode_line(c, indent, effortful=False)
            # feeding loop: supply present -> top up the relief (and feel the hit)
            self.emit(f"{indent}loop feeding_{cr.name} @{c.clock} {{",
                      f"{indent}  prior:      predict(0)",
                      f"{indent}  sense:      {cr.supply}",
                      f"{indent}  precision:  0.9",
                      f"{indent}  conviction: 0.2{fmode}",
                      f"{indent}  act {{")
            self.emit(f"{indent}    move ! set({cr.relief}, 10) when {cr.supply} > 3")
            if cr.fed_feeling:
                self.emit(f"{indent}    emit feel({cr.fed_feeling}) when {cr.supply} > 3")
            self.emit(f"{indent}  }}", f"{indent}}}", "")
            # hunger loop: relief drained below threshold -> the ache
            hmode = self._mode_line(c, indent, effortful=False)
            self.emit(f"{indent}loop hungering_{cr.name} @{c.clock} {{",
                      f"{indent}  prior:      predict(10)",
                      f"{indent}  sense:      {cr.relief}",
                      f"{indent}  precision:  0.85",
                      f"{indent}  conviction: 0.3{hmode}",
                      f"{indent}  act {{")
            if c._budget is not None:
                self.emit(f"{indent}    move ! spend({c.name}_budget, "
                          f"{_num(c.temp.feeling_cost)}) when {cr.relief} < {_num(cr.threshold)}")
            self.emit(f"{indent}    emit feel({cr.feeling}) when {cr.relief} < {_num(cr.threshold)}",
                      f"{indent}  }}", f"{indent}}}", "")

    def _lie_loops(self, c, indent):
        """The Lie: a high-conviction belief loop that reads the very evidence
        that would disconfirm it and, because conviction outranks that evidence,
        suppresses it (routes to `act`) again and again -- self-deception. Each
        suppression hardens it (`learn`). If it is breakable, the raw weight of the
        suppressed evidence accumulates until it `overwhelm`s the conviction and
        the loop is forced to perceive: the belief updates toward the truth and a
        `_seen` channel is raised -- the self-revelation. The lie also emits the
        ache it exists to keep down, whenever the evidence is low (its own world)."""
        for l in c._lies:
            lid = _ident(l.name)
            mode = self._mode_line(c, indent, effortful=False)
            if l.overwhelm_auto:
                ov = f"\n{indent}  overwhelm:  auto"
            elif l.overwhelm and l.overwhelm > 0:
                ov = f"\n{indent}  overwhelm:  {_num(l.overwhelm)}"
            else:
                ov = ""
            self.emit(f"{indent}loop the_lie_{lid} @{c.clock} {{",
                      f"{indent}  prior:      predict({_num(l.expects)})",
                      f"{indent}  sense:      {l.evidence}",
                      f"{indent}  precision:  0.35",
                      f"{indent}  conviction: {_num(l.conviction)}",
                      f"{indent}  learn:      {_num(l.learn)}{ov}{mode}",
                      f"{indent}  act {{",
                      f"{indent}    update -> the_truth_about_{lid}",
                      f"{indent}    emit feel({l.feeling}) when {l.evidence} < {_num(l.threshold)}",
                      f"{indent}    move ! set({lid}_seen, 9) when perceiving",
                      f"{indent}  }}", f"{indent}}}", "")

    def _need_loops(self, c, indent):
        """The Need: what the character must reach to become whole, the opposite of
        the Lie. It is honest -- high precision, low conviction, so it perceives --
        and it reads only the `_seen` channel the lie raises at its revelation. Its
        prior sits at the midpoint, so it fires at both extremes: the unmet ache
        while `_seen` is low, and (if named) the fed-feeling once `_seen` rises. It
        is never fed by getting the want -- only by the lie being seen."""
        for n in c._needs:
            mode = self._mode_line(c, indent, effortful=False)
            self.emit(f"{indent}loop the_need_{_ident(n.name)} @{c.clock} {{",
                      f"{indent}  prior:      predict(5)",
                      f"{indent}  sense:      {n.seen_channel}",
                      f"{indent}  precision:  0.85",
                      f"{indent}  conviction: 0.25{mode}",
                      f"{indent}  act {{")
            self.emit(f"{indent}    emit feel({n.feeling}) when {n.seen_channel} < 3")
            if n.fed_feeling:
                self.emit(f"{indent}    emit feel({n.fed_feeling}) when {n.seen_channel} > 5")
            self.emit(f"{indent}  }}", f"{indent}}}", "")

    def _confidence_loops(self, c, indent):
        """A belief held because everyone else is seen to hold it. Its conviction
        is not a constant but reads the shared field: while most of the group is
        holding, conviction is high (`together`) and the belief is unshakeable;
        as the field thins, conviction falls toward `alone`, and past the tipping
        point the holder lets go too -- which thins the field further, for the
        next holder. That is the cascade: doctrine, war-paper, the bank run.

        The holder exposes its own holding on the field channel (`.<tag>`), high
        while it holds and dropping to zero when it lets go, so that every other
        holder reads this one's defection in the same field."""
        step = _dur(self.s.step)
        for cf in c._confidences:
            # The holding is a FLOW, not a firing loop, because confidence must
            # be re-checked against the crowd EVERY moment -- a firing loop only
            # acts when its own sense diverges from its belief, and a holder that
            # still holds has no divergence to notice the crowd thinning. The
            # flow reads the field each frame and drives this holder's holding
            # toward the crowd: full while enough others hold (field above the
            # herd line TIP), zero once the field thins past it or a private
            # doubt has landed. That is the whole mechanism -- belief about other
            # people's belief -- and it cascades because each holder that lets go
            # lowers the field the next one reads.
            tip = round(cf.belief * 0.85, 4)   # the herd line: ~15% gone tips it
            rate = round(2.5 / step, 4)        # collapses over a couple of beats
            doubt = f"{cf.name}_doubt"
            # target = believing while (field>TIP and not doubting) else 0.
            # comparisons yield 1.0/0.0, so this is a plain arithmetic gate.
            target = (f"{_num(cf.belief)} * (field({cf.tag}) > {_num(tip)}) "
                      f"* ({doubt} < 1)")
            self.emit(f"{indent}flow {cf.tag} @{c.clock} {{ dynamics: "
                      f"{_num(rate)} * (({target}) - {cf.tag}) }}", "")
            # a light loop so the holding is felt and narratable: resolve while
            # the belief holds, and its loss when the holder finally lets go.
            hmode = self._mode_line(c, indent, effortful=False)
            self.emit(f"{indent}loop holding_{cf.name} @{c.clock} {{",
                      f"{indent}  prior:      predict(0)",
                      f"{indent}  sense:      {cf.tag}",
                      f"{indent}  precision:  0.8",
                      f"{indent}  conviction: 0.3{hmode}",
                      f"{indent}  act {{",
                      f"{indent}    emit feel(resolve) when {cf.tag} > {_num(tip)}",
                      f"{indent}  }}", f"{indent}}}", "")

    def _steady_drive(self, c, indent):
        """A character who `steadies` others holds a calm surface high, so the
        world (and the ones leaning on them) can read the steadiness. Emitted as
        an allostat pinning the surface up -- a steady hand, held steady."""
        steady = getattr(c, "_steady_surface", None)
        if steady:
            surface, value = steady
            self.emit(f"{indent}allostat holding_steady_{c.name} {{ "
                      f"regulate: {surface}  setpoint: {_num(value)}  gain: 0.6 }}", "")

    def _feeling_loops(self, c, indent):
        for f in c._feelings:
            fmode = self._mode_line(c, indent, effortful=False)
            self.emit(f"{indent}loop feeling_{f.quale} @{c.clock} {{",
                      f"{indent}  prior:      predict({_num(f.resting)})",
                      f"{indent}  sense:      {f.from_channel}",
                      f"{indent}  precision:  {_num(f.precision)}",
                      f"{indent}  conviction: {_num(f.conviction)}{fmode}",
                      f"{indent}  act {{")
            guard = f" when {f.from_channel} > {_num(f.threshold)}"
            if c._budget is not None:
                self.emit(f"{indent}    move ! spend({c.name}_budget, "
                          f"{_num(f.cost)}){guard}")
            self.emit(f"{indent}    emit feel({f.quale}){guard}",
                      f"{indent}  }}", f"{indent}}}", "")

    def _memories(self, c, indent):
        for m in c._memories:
            self.emit(f"{indent}memory somatic {m.name} {{",
                      f"{indent}  cue: {m.cue}",
                      f"{indent}  when: {m.cue} > {_num(m.threshold)}",
                      f"{indent}  evoke: feel({m.evokes})",
                      f"{indent}  strength: 1.0",
                      f"{indent}}}", "")

    def _handlers(self, c, indent, scoped=None):
        for i, d in enumerate(c._dissoc):
            watch = f"{scoped}.{d.watches}" if scoped else d.watches
            self.emit(f"{indent}handle overwhelm_{c.name}_{i} with {{",
                      f"{indent}  when error({watch}) > {_num(d.tolerance)} :",
                      f"{indent}    dissociate({d.modality}) with precision "
                      f"-> titrate(0.05)",
                      f"{indent}  after {d.repair_after} :",
                      f"{indent}    repair {{ reattach({d.modality}) with "
                      f"precision -> titrate(0.1) }}",
                      f"{indent}}}", "")

    def _narrator(self, c, indent, scoped=None):
        # the lie is spoken (it is the cover story); the need is left unvoiced (it
        # is the body-truth the lie speaks over). So a believed lie automatically
        # produces a confabulation gap against the need aching underneath.
        lie_voice = {l.feeling: l.says for l in c._lies if l.says}
        has_voice = bool(c._narrator) or bool(lie_voice)
        if not has_voice:
            return
        loop_names = [a.name for a in c._appraisals] + \
                     [f"feeling_{f.quale}" for f in c._feelings] + \
                     [f"upholding_{v.name}" for v in c._values] + \
                     [f"the_lie_{_ident(l.name)}" for l in c._lies]
        if scoped:
            loop_names = [f"{scoped}.{n}" for n in loop_names]
        if not loop_names:
            return
        subs = ", ".join(loop_names)
        nm = f"self_{c.name}" if len(self.s.characters) > 1 else "self"
        line = f"{indent}narrator {nm} subscribes {{ {subs} }} confabulates true"
        voice = dict(lie_voice)
        voice.update((c._narrator or {}).get("voice") or {})   # author's voice wins
        self.emit(line)
        if voice:
            items = "  ".join(f'{q}: "{_esc(t)}"' for q, t in voice.items())
            self.emit(f"{indent}  voice {{ {items} }}")
        self.emit("")

    def _stimuli(self):
        multi = len(self.s.characters) > 1
        by_channel = {}
        for (t, who, ch, val) in self.s._events:
            key = f"{who.name}.{ch}" if (multi and who) else ch
            by_channel.setdefault(key, []).append((t, val))
        for ch, evs in by_channel.items():
            evs.sort(key=lambda x: _dur(x[0]))
            body = "  ".join(f"at {t}: {_num(v)}" for (t, v) in evs)
            self.emit(f"stimulus {ch} {{ {body} }}")
        if by_channel:
            self.emit("")

    def _couples(self):
        multi = len(self.s.characters) > 1
        for c in self.s.characters:
            for r in c._readings:
                src = f"{r.other}.{r.their_surface}"
                dst = f"{c.name}.{r.my_channel}" if multi else r.my_channel
                self.emit(f"couple {src} -> {dst} {{ gain {_num(r.gain)}  "
                          f"lag {r.lag} }}")
        if any(c._readings for c in self.s.characters):
            self.emit("")


# ---- helpers --------------------------------------------------------------
def _num(x):
    if isinstance(x, float) and x.is_integer():
        return str(int(x))
    return str(x)


def _esc(s):
    return s.replace('"', '\\"')


def _dur(s):
    if isinstance(s, (int, float)):
        return float(s)
    units = {"ms": 1e-3, "s": 1.0, "m": 60.0, "h": 3600.0, "d": 86400.0,
             "y": 31_536_000.0}
    s = str(s).strip()
    for u in ("ms", "s", "m", "h", "d", "y"):
        if s.endswith(u):
            return float(s[:-len(u)]) * units[u]
    return float(s)


def _blank_sense():
    from .story import _Sense
    return _Sense("heart", "intero", 70.0, "BPM")
